// Aestra Actions v2 — context-aware play screen and large action detail cards.
(function(){
 const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), norm=v=>String(v||'').trim().toLowerCase();
 const rows=id=>[...($(id)?.querySelectorAll('.entry-row')||[])], vals=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
 const favKey=()=>`aestra-favs:${norm($('charName')?.value)||'character'}`, favs=()=>{try{return new Set(JSON.parse(localStorage.getItem(favKey())||'[]'))}catch{return new Set()}}, save=s=>localStorage.setItem(favKey(),JSON.stringify([...s]));
 function handState(){let used=0;for(const r of rows('equipmentEditor')){const v=vals(r),notes=v[5]||'',stored=/§AESTRAEQ:/.test(notes)||norm(v[0]).startsWith('loadout');if(stored)continue;const text=norm(`${v[0]} ${v[1]} ${notes}`);if(/two[- ]?hand/.test(text)){used=2;break}if(/shield/.test(text)||/main hand|off hand|weapon|sword|dagger|spear|axe|bow|crossbow|gun|pistol|staff|tome|hammer|whip|knuckle|shuriken|rapier|katana/.test(text))used=Math.min(2,used+1)}return {used,empty:Math.max(0,2-used)}}
 function unarmed(){const h=handState();if(!h.empty)return [];return [{id:'system:unarmed',type:'attack',system:true,name:'Unarmed Strike',meta:`System Weapon · Brawling · One-handed · Melee · ${h.empty} empty hand${h.empty===1?'':'s'}`,summary:'【DEX + MIG】 · 【HR + 0】 physical',detail:`Accuracy: 【DEX + MIG】\nDamage: 【HR + 0】 physical\nBrawling · One-handed · Melee\n\nAn unarmed strike is automatically equipped in each empty hand slot. This is a built-in character option and is not purchased, sold or removed.`} ]}
 function weapons(){return [...rows('equipmentEditor').map((r,i)=>{const v=vals(r),notes=v[5]||'',stored=/§AESTRAEQ:/.test(notes)||norm(v[0]).startsWith('loadout'),isWeapon=/weapon|hand|sword|dagger|spear|axe|bow|crossbow|gun|pistol|staff|tome|hammer|whip|knuckle|shuriken|rapier|katana/i.test(`${v[0]} ${v[1]} ${notes}`);if(stored||!isWeapon)return null;const acc=notes.match(/Accuracy\s+([^·\n]+)/i)?.[1]?.trim()||notes.match(/\[(MIG|DEX|INS|WLP)[^\]]*\]/i)?.[0]||'',damage=notes.match(/Damage\s+([^·\n]+)/i)?.[1]?.trim()||'',range=notes.match(/\b(Melee|Ranged)\b/i)?.[1]||'';return{id:`weapon:${i}:${v[1]}`,type:'attack',name:v[1]||'Unnamed Weapon',meta:[acc,range].filter(Boolean).join(' · ')||v[0],summary:damage?`Damage ${damage}`:'Tap for weapon details',detail:notes||'No additional weapon rules entered.',cost:''}}).filter(Boolean),...unarmed()]}
 function spells(){return rows('spellsEditor').map((r,i)=>{const v=vals(r);return{id:`spell:${i}:${v[0]}`,type:'magic',name:v[0]||'Unnamed Spell',meta:[v[2],v[3]].filter(Boolean).join(' · '),summary:v[4]||'No effect entered.',detail:v[4]||'No effect entered.',cost:v[1]?`${v[1]} MP`:''}})}
 function skills(){return rows('skillsEditor').map((r,i)=>{const v=vals(r);return{id:`skill:${i}:${v[0]}`,type:'skill',name:v[0]||'Unnamed Skill',meta:[v[2],v[1]&&`SL ${v[1]}`].filter(Boolean).join(' · '),summary:v[3]||'No effect entered.',detail:v[3]||'No effect entered.',cost:''}}).filter(x=>x.detail&&x.detail!=='No effect entered.')}
 const basics=[
 {id:'basic:attack',type:'action',system:true,name:'Attack',meta:'System Action · Core',summary:'Attack with one of your available weapons.',detail:'Choose a target you can see and reach with the weapon. Perform the weapon’s Accuracy Check against the target’s Defense; on a hit, deal the weapon’s listed damage.'},
 {id:'basic:equipment',type:'action',system:true,name:'Equipment',meta:'System Action · Core',summary:'Change equipped items during a conflict.',detail:'Store or equip any number of eligible items as one action. Armor normally cannot be equipped or removed within a single action.'},
 {id:'basic:guard',type:'action',system:true,name:'Guard',meta:'System Action · Core',summary:'Gain broad protection until your next turn.',detail:'Until the start of your next turn, gain Resistance to all damage and +2 to Opposed Checks. You may also cover another creature, preventing melee attacks from targeting them while the cover lasts.'},
 {id:'basic:hinder',type:'action',system:true,name:'Hinder',meta:'System Action · Core',summary:'Put an opponent at a disadvantage.',detail:'Describe how you interfere with the target, then make a Check against DL 10 using Attributes chosen by the GM. On success, inflict dazed, shaken, slow or weak.'},
 {id:'basic:inventory',type:'action',system:true,name:'Inventory',meta:'System Action · Core',summary:'Produce and immediately use an inventory item.',detail:'Use an inventory item as part of the same action. If reaching the target is obstructed, the GM may call for a Check. This action can be used even while both hands are occupied.'},
 {id:'basic:objective',type:'action',system:true,name:'Objective',meta:'System Action · Core',summary:'Make progress toward a goal or Clock.',detail:'Describe what you want to achieve and your approach. Objective always requires a Check; on success, it advances or erases sections of the relevant Clock according to the Result.'},
 {id:'basic:study',type:'action',system:true,name:'Study',meta:'System Action · Core',summary:'Learn useful information about a subject.',detail:'State what you want to learn, then perform an Open Check, generally 【INS + INS】 unless another approach makes more sense. Higher Results reveal increasingly complete information; you cannot ask the exact same question about that subject again.'},
 {id:'basic:spell',type:'action',system:true,name:'Spell',meta:'System Action · Core',summary:'Cast a spell you have learned.',detail:'Use this action to cast one of your learned spells. Open the Magic tab in Actions to see the spells currently available to your character.'},
 {id:'basic:skill',type:'action',system:true,name:'Skill',meta:'System Action · Core',summary:'Activate a Skill that requires an action.',detail:'Some Skills explicitly require you to use an action to activate them. Open the Skills tab to see your character’s learned Skills.'},
 {id:'basic:other',type:'action',system:true,name:'Other',meta:'System Action · Core',summary:'Attempt a reasonable creative action.',detail:'For actions not covered elsewhere, describe what you want to do and resolve it with the GM. If an existing action already fits, use that action instead.'}
 ];
 function inventory(){return rows('inventoryEditor').map((r,i)=>{const v=vals(r);return{id:`item:${i}:${v[0]}`,type:'item',name:v[0]||'Unnamed Item',meta:v[1]?`Qty ${v[1]}`:'Inventory',summary:v[2]||'Inventory item',detail:v[2]||'No additional item rules entered.',cost:''}}).filter(x=>x.name!=='Unnamed Item')}
 function all(){return [...weapons(),...spells(),...skills(),...inventory(),...basics]}
 function icon(t){return({attack:'⚔',magic:'✦',skill:'◆',item:'◇',action:'◈'})[t]||'◆'}
 function card(a){const f=favs().has(a.id);return `<article class="a2-card ${a.system?'a2-system':''}" data-a2-id="${esc(a.id)}"><button class="a2-star ${f?'on':''}" data-a2-star type="button">${f?'★':'☆'}</button><button class="a2-open" data-a2-open type="button"><span class="a2-kind">${icon(a.type)} ${esc(a.type.toUpperCase())}${a.system?' · SYSTEM':''}</span><strong>${esc(a.name)}</strong>${a.cost?`<b class="a2-cost">${esc(a.cost)}</b>`:''}<small>${esc(a.meta)}</small><p>${esc(a.summary)}</p><span class="a2-more">View details ›</span></button></article>`}
 function render(mode){const host=$('sessionActionBody');if(!host)return;let list=all();if(mode==='favourites')list=list.filter(x=>favs().has(x.id));if(mode==='attacks')list=list.filter(x=>x.type==='attack');if(mode==='spells')list=list.filter(x=>x.type==='magic');if(mode==='skills')list=list.filter(x=>x.type==='skill');if(mode==='items')list=list.filter(x=>x.type==='item');if(mode==='basic')list=list.filter(x=>x.type==='action');host.dataset.mode=mode;host.innerHTML=list.map(card).join('')||`<div class="action-empty">${mode==='favourites'?'Star useful actions to put them here.':'Nothing available here yet.'}</div>`;document.querySelectorAll('.session-action-tab').forEach(b=>b.classList.toggle('active',b.dataset.actionTab===mode))}
 function modal(){let m=$('a2Modal');if(m)return m;m=document.createElement('div');m.id='a2Modal';m.className='a2-modal hidden';m.innerHTML='<div class="a2-dialog"><button class="a2-close" type="button">×</button><div id="a2Detail"></div></div>';document.body.appendChild(m);m.querySelector('.a2-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
 function open(a){const m=modal(),d=$('a2Detail');d.innerHTML=`<p class="a2-detail-kind">${icon(a.type)} ${esc(a.type.toUpperCase())}${a.system?' · SYSTEM':''}</p><h2>${esc(a.name)}</h2><div class="a2-detail-meta">${a.cost?`<strong>${esc(a.cost)}</strong>`:''}<span>${esc(a.meta)}</span></div><div class="a2-rule">${esc(a.detail).replace(/\n/g,'<br>')}</div>`;m.classList.remove('hidden')}
 function install(){const sec=$('sessionActions');if(!sec)return;sec.querySelector('.session-actions-head small').textContent='Your play screen';const tabs=sec.querySelector('.session-action-tabs');tabs.innerHTML='<button type="button" class="session-action-tab active" data-action-tab="favourites">★ Quick</button><button type="button" class="session-action-tab" data-action-tab="attacks">Attacks</button><button type="button" class="session-action-tab" data-action-tab="spells">Magic</button><button type="button" class="session-action-tab" data-action-tab="skills">Skills</button><button type="button" class="session-action-tab" data-action-tab="items">Items</button><button type="button" class="session-action-tab" data-action-tab="basic">Actions</button>';
 sec.addEventListener('click',e=>{const tab=e.target.closest('[data-action-tab]');if(tab){e.stopImmediatePropagation();render(tab.dataset.actionTab);return}const star=e.target.closest('[data-a2-star]');if(star){e.stopImmediatePropagation();const id=star.closest('[data-a2-id]').dataset.a2Id,s=favs();s.has(id)?s.delete(id):s.add(id);save(s);render($('sessionActionBody').dataset.mode||'favourites');return}const op=e.target.closest('[data-a2-open]');if(op){e.stopImmediatePropagation();const id=op.closest('[data-a2-id]').dataset.a2Id,a=all().find(x=>x.id===id);if(a)open(a)}},true);
 const style=document.createElement('style');style.id='actionsV2Styles';style.textContent=`#sessionActionBody{grid-template-columns:repeat(2,minmax(0,1fr))!important}.a2-card{position:relative;min-width:0;border:1px solid rgba(211,171,91,.2);border-radius:13px;background:linear-gradient(135deg,rgba(16,22,29,.78),rgba(26,20,27,.74));overflow:hidden}.a2-card.a2-system{border-style:dashed;background:linear-gradient(135deg,rgba(12,20,27,.82),rgba(20,18,23,.74))}.a2-open{display:grid!important;width:100%!important;min-height:132px!important;padding:12px!important;text-align:left!important;border:0!important;background:transparent!important;grid-template-columns:1fr auto;align-content:start;gap:3px 8px}.a2-kind{grid-column:1/-1;font-size:.5rem;letter-spacing:.16em;color:#cda85d}.a2-system .a2-kind{color:#8db9cf}.a2-open strong{color:#e6d6ad;font-family:Georgia,serif;font-size:.92rem}.a2-cost{color:#8bc7e9;font-size:.68rem}.a2-open small,.a2-open p,.a2-more{grid-column:1/-1}.a2-open small{font-size:.61rem;color:#9f927c}.a2-open p{margin:5px 0 0;font-size:.7rem;line-height:1.35;color:#b8afa0}.a2-more{margin-top:4px;font-size:.58rem;color:#b89655;opacity:.75}.a2-star{position:absolute!important;z-index:2;right:5px;top:5px;width:28px!important;height:28px!important;min-height:0!important;padding:0!important;border:0!important;background:transparent!important;color:#82765e!important}.a2-star.on{color:#e1bd69!important}.a2-open>strong{padding-right:22px}.a2-modal{position:fixed;inset:0;z-index:1800;display:grid;place-items:center;padding:14px;background:rgba(2,4,8,.86)}.a2-modal.hidden{display:none!important}.a2-dialog{position:relative;width:min(570px,96vw);max-height:86vh;overflow:auto;padding:25px 22px;border:1px solid rgba(211,171,91,.38);border-radius:18px;background:linear-gradient(145deg,#10151d,#1a141b);box-shadow:0 30px 90px rgba(0,0,0,.6)}.a2-close{position:absolute!important;right:10px;top:10px;width:34px!important;height:34px!important;min-height:0!important;padding:0!important;border-radius:50%!important}.a2-detail-kind{margin:0;color:#cda85d;font-size:.6rem;letter-spacing:.16em}.a2-dialog h2{margin:5px 42px 8px 0;color:#ead9ad;font-family:Georgia,serif;font-size:1.6rem}.a2-detail-meta{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:15px;font-size:.72rem;color:#aaa08f}.a2-detail-meta strong{color:#8bc7e9}.a2-rule{padding:14px;border:1px solid rgba(211,171,91,.16);border-radius:11px;background:rgba(0,0,0,.15);color:#d2c7b4;font-size:.84rem;line-height:1.55}@media(max-width:640px){#sessionActionBody{grid-template-columns:1fr!important}.a2-open{min-height:112px!important}.a2-dialog{padding:21px 15px}}`;document.head.appendChild(style);
 ['equipmentEditor','spellsEditor','skillsEditor','inventoryEditor'].forEach(id=>{$(id)?.addEventListener('input',()=>requestAnimationFrame(()=>render($('sessionActionBody').dataset.mode||'favourites')))});document.addEventListener('aestra:equipment-changed',()=>requestAnimationFrame(()=>render($('sessionActionBody').dataset.mode||'favourites')));render('favourites')}
 setTimeout(install,0);setTimeout(()=>{if(!$('actionsV2Styles'))install()},600);
})();