if(!document.getElementById('gmSaveBtn')){
  const legacy=document.createElement('button');
  legacy.id='gmSaveBtn';
  legacy.type='button';
  legacy.className='hidden';
  document.body.appendChild(legacy);
}
await import('./app-core.js?v=1');
await import('./gm-structured.js?v=1');
await import('./enhancements.js?v=2');
await import('./status-fix.js?v=2');
await import('./core-library.js?v=4');
await import('./rules-aware.js?v=3');
await import('./aestra-visuals.js?v=2');
await import('./aestra-theme.js?v=1');
await import('./resource-glow.js?v=1');
await import('./compact-attributes.js?v=2');
await import('./compact-ip.js?v=1');
await import('./magic-effects.js?v=2');
await import('./build-menu.js?v=3');
await import('./ui-icons.js?v=2');
await import('./remove-controls.js?v=1');
await import('./skill-levels.js?v=2');
await import('./class-mastery.js?v=1');
await import('./picker-icons.js?v=2');
await import('./build-entry-icons.js?v=2');
await import('./unique-icons.js?v=1');
await import('./point-orbs.js?v=3');
await import('./sheet-polish.js?v=1');
await import('./conditions-collapse.js?v=3');
await import('./combat-ui-polish.js?v=1');
await import('./save-orb.js?v=1');
await import('./rules-orb.js?v=2');
await import('./grand-ui.js?v=1');
await import('./mobile-pages.js?v=1');
await import('./status-label-polish.js?v=1');
await import('./portrait-upload.js?v=1');
await import('./mobile-character-polish.js?v=1');
