const CONFIG=window.AESTRA_CONFIG||{};
const STATUS_OPTIONS=['Slow','Dazed','Weak','Shaken','Enraged','Poisoned'];
const DEMO_KEY='aestra-character-demo-v2';
const els=Object.fromEntries([...document.querySelectorAll('[id]')].map(el=>[el.id,el]));
let supabase=null,currentUser=null,currentCharacterId=null,isDemo=false,isGM=false;
let supabaseInitPromise=null;
let gmCharacters=[],gmEditingCharacter=null,gmEditingStatuses=[];
const emptyState=()=>({name:'Iris',player_name:'Player',identity:'',theme:'',origin:'',level:5,portrait_url:'',mig:'d8',dex:'d10',ins:'d8',wlp:'d10',mig_base:'d8',dex_base:'d10',ins_base:'d8',wlp_base:'d10',hp_current:0,hp_max:0,mp_current:0,mp_max:0,ip_current:0,ip_max:0,fabula_points:3,hp_other:0,mp_other:0,ip_other:0,xp:0,zenit:0,initiative:0,defence:10,magic_defence:10,crisis:0,initiative_other:0,defence_other:0,magic_defence_other:0,statuses:[],traits:['','',''],classes_struct:[],skills_struct:[],equipment_struct:[],spells_struct:[],bonds_struct:[],inventory_struct:[],classes:'',skills:'',equipment:'',spells:'',bonds:'',notes:''});
const state=emptyState();
const clamp=(n,min,max)=>{n=Number(n);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):min};
const die=v=>Number(String(v||'d6').replace('d',''))||6;
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const configured=()=>Boolean(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey);
const num=id=>Number(els[id]?.value)||0;
const txt=id=>els[id]?.value?.trim?.()||'';
function markDirty(){if(els.saveStatus)els.saveStatus.textContent='Unsaved changes'}
function setAuth(t){if(els.authMessage)els.authMessage.textContent=t||''}
function ensureArrays(){for(const k of ['traits','classes_struct','skills_struct','equipment_struct','spells_struct','bonds_struct','inventory_struct','statuses'])if(!Array.isArray(state[k]))state[k]=[];while(state.traits.length<3)state.traits.push('')}
function calcDerived(){
 state.hp_max=Math.max(1,die(state.mig_base)*5+Number(state.level||0)+Number(state.hp_other||0));
 state.mp_max=Math.max(0,die(state.wlp_base)*5+Number(state.level||0)+Number(state.mp_other||0));
 state.ip_max=Math.max(0,6+Number(state.ip_other||0));
 state.crisis=Math.floor(state.hp_max/2);
 const eq=(state.equipment_struct||[]).reduce((a,x)=>({init:a.init+(Number(x.initiative)||0),def:a.def+(Number(x.defence)||0),mdef:a.mdef+(Number(x.magic_defence)||0)}),{init:0,def:0,mdef:0});
 state.initiative=Number(state.initiative_other||0)+eq.init;
 state.defence=die(state.dex)+Number(state.defence_other||0)+eq.def;
 state.magic_defence=die(state.ins)+Number(state.magic_defence_other||0)+eq.mdef;
 state.hp_current=clamp(state.hp_current,0,state.hp_max);state.mp_current=clamp(state.mp_current,0,state.mp_max);state.ip_current=clamp(state.ip_current,0,state.ip_max);
}
function renderDerived(){calcDerived();for(const r of ['hp','mp','ip']){if(els[`${r}Now`])els[`${r}Now`].textContent=state[`${r}_current`];if(els[`${r}MaxText`])els[`${r}MaxText`].textContent=state[`${r}_max`];if(els[`${r}Bar`])els[`${r}Bar`].style.width=`${state[`${r}_max`]?state[`${r}_current`]/state[`${r}_max`]*100:0}%`}if(els.hpFormula)els.hpFormula.textContent=`d${die(state.mig_base)} × 5 + ${state.level} + ${state.hp_other} Other`;if(els.mpFormula)els.mpFormula.textContent=`d${die(state.wlp_base)} × 5 + ${state.level} + ${state.mp_other} Other`;if(els.ipFormula)els.ipFormula.textContent=`6 + ${state.ip_other} Other`;if(els.fpText)els.fpText.textContent=state.fabula_points;if(els.initiativeText)els.initiativeText.textContent=state.initiative;if(els.defenceText)els.defenceText.textContent=state.defence;if(els.magicDefenceText)els.magicDefenceText.textContent=state.magic_defence;if(els.crisisText)els.crisisText.textContent=state.crisis}
function renderPortrait(){const u=state.portrait_url||'';if(!els.portraitUrl)return;els.portraitUrl.value=u;if(u){els.portraitImg.src=u;els.portraitImg.classList.remove('hidden');els.portraitFallback.classList.add('hidden')}else{els.portraitImg.classList.add('hidden');els.portraitFallback.classList.remove('hidden');els.portraitFallback.textContent=(state.name||'?')[0]?.toUpperCase()||'?'}}
function renderStatuses(){if(!els.statuses)return;els.statuses.innerHTML='';STATUS_OPTIONS.forEach(s=>{const b=document.createElement('button');b.type='button';b.className='status-chip';b.textContent=s;b.classList.toggle('active',state.statuses.includes(s));b.onclick=()=>{state.statuses.includes(s)?state.statuses=state.statuses.filter(x=>x!==s):state.statuses.push(s);renderStatuses();markDirty()};els.statuses.appendChild(b)})}
function rowButton(label,fn){const b=document.createElement('button');b.type='button';b.className='ghost remove-entry';b.textContent=label;b.onclick=fn;return b}
function inp(value,placeholder,type='text'){const e=document.createElement('input');e.type=type;e.value=value??'';e.placeholder=placeholder||'';return e}
function textarea(value,placeholder){const e=document.createElement('textarea');e.rows=2;e.value=value??'';e.placeholder=placeholder||'';return e}
function editor(container,key,fields){const root=els[container];if(!root)return;root.innerHTML='';state[key].forEach((item,i)=>{const row=document.createElement('div');row.className='entry-row';fields.forEach(f=>{const wrap=document.createElement('label');wrap.textContent=f.label;const e=f.long?textarea(item[f.k],f.placeholder):inp(item[f.k],f.placeholder,f.type);e.oninput=()=>{item[f.k]=f.type==='number'?Number(e.value)||0:e.value;renderDerived();markDirty();if(key==='classes_struct')renderClassSummary()};wrap.appendChild(e);row.appendChild(wrap)});row.appendChild(rowButton('Remove',()=>{state[key].splice(i,1);renderStructured();renderDerived();markDirty()}));root.appendChild(row)})}
function renderTraits(){if(!els.traitsEditor)return;els.traitsEditor.innerHTML='';for(let i=0;i<3;i++){const l=document.createElement('label');l.textContent=`Trait ${i+1}`;const e=inp(state.traits[i],'e.g. Stubborn heir');e.oninput=()=>{state.traits[i]=e.value;markDirty()};l.appendChild(e);els.traitsEditor.appendChild(l)}}
function renderClassSummary(){if(!els.classLevelSummary)return;const total=(state.classes_struct||[]).reduce((s,x)=>s+(Number(x.level)||0),0);els.classLevelSummary.textContent=`Class levels: ${total} / Character level ${state.level}${total!==Number(state.level)?' · check totals':''}`}
function renderStructured(){renderTraits();editor('classesEditor','classes_struct',[{k:'name',label:'Class',placeholder:'Class name'},{k:'level',label:'Level',type:'number'},{k:'benefits',label:'Free Benefits / Notes',long:true}]);editor('skillsEditor','skills_struct',[{k:'name',label:'Skill',placeholder:'Skill name'},{k:'rank',label:'SL',type:'number'},{k:'source',label:'Class / Source'},{k:'effect',label:'Effect',long:true}]);editor('equipmentEditor','equipment_struct',[{k:'slot',label:'Slot',placeholder:'Main hand / Armor / Accessory'},{k:'name',label:'Item'},{k:'defence',label:'DEF +',type:'number'},{k:'magic_defence',label:'MDEF +',type:'number'},{k:'initiative',label:'INIT +',type:'number'},{k:'notes',label:'Rules / Description',long:true}]);editor('spellsEditor','spells_struct',[{k:'name',label:'Spell / Arcana'},{k:'mp',label:'MP',type:'number'},{k:'targets',label:'Targets'},{k:'duration',label:'Duration'},{k:'effect',label:'Effect',long:true}]);editor('bondsEditor','bonds_struct',[{k:'subject',label:'Person / Faction / Ideal'},{k:'strength',label:'Strength',type:'number'},{k:'feelings',label:'Feelings',placeholder:'Admiration, loyalty…'},{k:'notes',label:'Notes',long:true}]);editor('inventoryEditor','inventory_struct',[{k:'name',label:'Item'},{k:'qty',label:'Qty',type:'number'},{k:'notes',label:'Notes',long:true}]);renderClassSummary()}
function renderForm(){ensureArrays();const map={charName:'name',playerName:'player_name',identity:'identity',theme:'theme',origin:'origin',level:'level',xp:'xp',zenit:'zenit',mig:'mig',dex:'dex',ins:'ins',wlp:'wlp',migBase:'mig_base',dexBase:'dex_base',insBase:'ins_base',wlpBase:'wlp_base',hpOther:'hp_other',mpOther:'mp_other',ipOther:'ip_other',initiativeOther:'initiative_other',defenceOther:'defence_other',magicDefenceOther:'magic_defence_other',classes:'classes',skills:'skills',equipment:'equipment',spells:'spells',bonds:'bonds',notes:'notes'};Object.entries(map).forEach(([id,k])=>{if(els[id])els[id].value=state[k]??''});renderPortrait();renderStatuses();renderStructured();renderDerived()}
function pullForm(){const textMap={charName:'name',playerName:'player_name',identity:'identity',theme:'theme',origin:'origin',mig:'mig',dex:'dex',ins:'ins',wlp:'wlp',migBase:'mig_base',dexBase:'dex_base',insBase:'ins_base',wlpBase:'wlp_base',classes:'classes',skills:'skills',equipment:'equipment',spells:'spells',bonds:'bonds',notes:'notes'};Object.entries(textMap).forEach(([id,k])=>state[k]=txt(id));const nmap={level:'level',xp:'xp',zenit:'zenit',hpOther:'hp_other',mpOther:'mp_other',ipOther:'ip_other',initiativeOther:'initiative_other',defenceOther:'defence_other',magicDefenceOther:'magic_defence_other'};Object.entries(nmap).forEach(([id,k])=>state[k]=num(id));state.portrait_url=txt('portraitUrl');calcDerived()}
function showApp(){els.authView?.classList.add('hidden');els.appView?.classList.remove('hidden');els.logoutBtn?.classList.toggle('hidden',isDemo)}
function showAuth(){els.appView?.classList.add('hidden');els.authView?.classList.remove('hidden')}
async function ensureSupabase(){
 if(supabase)return supabase;
 if(!configured())throw new Error('Supabase is not configured.');
 if(!supabaseInitPromise){
  supabaseInitPromise=(async()=>{
   els.connectionBadge.textContent='Connecting…';
   const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');
   supabase=mod.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);
   els.connectionBadge.textContent='Supabase ready';
   return supabase;
  })().catch(err=>{supabaseInitPromise=null;supabase=null;els.connectionBadge.textContent='Connection failed';throw err});
 }
 return supabaseInitPromise;
}
async function initSupabase(){try{await ensureSupabase();const {data,error}=await supabase.auth.getSession();if(error)throw error;if(data.session){currentUser=data.session.user;await enterApp()}}catch(e){console.error('Supabase init failed',e);els.connectionBadge.textContent='Connection failed';setAuth('Could not connect to Supabase. Tap Sign in to retry.')}}
async function enterDemo(){isDemo=true;isGM=true;currentUser={id:'demo',email:'demo@local'};const saved=localStorage.getItem(DEMO_KEY);if(saved)try{Object.assign(state,JSON.parse(saved))}catch{};if(!state.hp_current)state.hp_current=die(state.mig_base)*5+state.level;if(!state.mp_current)state.mp_current=die(state.wlp_base)*5+state.level;if(!state.ip_current)state.ip_current=6;els.connectionBadge.textContent='Local demo';showApp();renderForm();await loadGMDashboard()}
async function enterApp(){isDemo=false;showApp();try{const {data:p,error:profileError}=await supabase.from('profiles').select('is_gm').eq('id',currentUser.id).maybeSingle();if(profileError)throw profileError;isGM=p?.is_gm===true;document.querySelector('[data-view="gm"]')?.classList.toggle('hidden',!isGM);els.connectionBadge.textContent=isGM?`GM · ${currentUser.email}`:currentUser.email;const {data,error}=await supabase.from('characters').select('*').eq('owner_id',currentUser.id).eq('campaign_id',CONFIG.campaignId).maybeSingle();if(error)throw error;if(data){Object.assign(state,data);currentCharacterId=data.id}else{Object.assign(state,emptyState());state.hp_current=die(state.mig_base)*5+state.level;state.mp_current=die(state.wlp_base)*5+state.level;state.ip_current=6}renderForm();if(isGM)await loadGMDashboard()}catch(e){console.error('Failed to load account',e);showAuth();setAuth(`Signed in, but the character sheet could not load: ${e.message||e}`)}}
async function saveCharacter(){pullForm();renderForm();if(isDemo){localStorage.setItem(DEMO_KEY,JSON.stringify(state));els.saveStatus.textContent='Saved locally';await loadGMDashboard();return}els.saveStatus.textContent='Saving…';const payload={...state,owner_id:currentUser.id,campaign_id:CONFIG.campaignId,updated_at:new Date().toISOString()};delete payload.id;delete payload.created_at;const r=currentCharacterId?await supabase.from('characters').update(payload).eq('id',currentCharacterId).select().single():await supabase.from('characters').insert(payload).select().single();if(r.error){els.saveStatus.textContent=`Save failed: ${r.error.message}`;return}currentCharacterId=r.data.id;Object.assign(state,r.data);els.saveStatus.textContent='Saved';if(isGM)await loadGMDashboard()}
function gmCard(c){const st=(c.statuses||[]).map(s=>`<span class="badge">${esc(s)}</span>`).join('')||'<span class="muted">No statuses</span>';return `<article class="panel gm-card" data-char-id="${c.id}"><div class="gm-name"><div><p class="eyebrow">${esc(c.player_name||'Player')}</p><h3>${esc(c.name||'Unnamed')}</h3></div><span class="badge">Lv ${Number(c.level)||1}</span></div><div class="mini-resources"><div class="mini"><span>HP</span><strong>${c.hp_current||0}/${c.hp_max||0}</strong></div><div class="mini"><span>MP</span><strong>${c.mp_current||0}/${c.mp_max||0}</strong></div><div class="mini"><span>IP</span><strong>${c.ip_current||0}/${c.ip_max||0}</strong></div><div class="mini"><span>FP</span><strong>${c.fabula_points||0}</strong></div></div><div class="chips">${st}</div><div class="gm-quick"><button data-quick="hp" data-delta="-1">HP −1</button><button data-quick="hp" data-delta="1">HP +1</button><button data-quick="fp" data-delta="1">FP +1</button></div><button class="secondary gm-open">Open sheet</button></article>`}
async function loadGMDashboard(){els.gmCards.innerHTML='<p class="muted">Loading characters…</p>';if(isDemo){gmCharacters=[{...state,id:'demo-character'}]}else{if(!isGM)return;const {data,error}=await supabase.from('characters').select('*').eq('campaign_id',CONFIG.campaignId).order('name');if(error){els.gmCards.innerHTML=`<p>${esc(error.message)}</p>`;return}gmCharacters=data||[]}els.gmCards.innerHTML=gmCharacters.length?gmCharacters.map(gmCard).join(''):'<article class="panel"><p class="muted">No saved characters yet.</p></article>';els.gmCards.querySelectorAll('.gm-card').forEach(card=>{const id=card.dataset.charId;card.querySelector('.gm-open').onclick=()=>openGmEditor(id);card.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>quickGmAdjust(id,b.dataset.quick,Number(b.dataset.delta)))})}
async function quickGmAdjust(id,k,d){const c=gmCharacters.find(x=>x.id===id);if(!c)return;const patch={updated_at:new Date().toISOString()};if(k==='hp')patch.hp_current=clamp((c.hp_current||0)+d,0,c.hp_max||0);if(k==='fp')patch.fabula_points=Math.max(0,(c.fabula_points||0)+d);if(isDemo){Object.assign(state,patch);await loadGMDashboard();return}const {error}=await supabase.from('characters').update(patch).eq('id',id);if(error)return alert(error.message);await loadGMDashboard()}
function renderGmStatuses(){els.gmStatuses.innerHTML='';STATUS_OPTIONS.forEach(s=>{const b=document.createElement('button');b.type='button';b.className='status-chip';b.textContent=s;b.classList.toggle('active',gmEditingStatuses.includes(s));b.onclick=()=>{gmEditingStatuses.includes(s)?gmEditingStatuses=gmEditingStatuses.filter(x=>x!==s):gmEditingStatuses.push(s);renderGmStatuses()};els.gmStatuses.appendChild(b)})}
function openGmEditor(id){const c=gmCharacters.find(x=>x.id===id);if(!c)return;gmEditingCharacter={...c};gmEditingStatuses=[...(c.statuses||[])];els.gmEditTitle.textContent=c.name||'Unnamed';els.gmEditPlayer.textContent=`Player: ${c.player_name||'Unknown'}`;const m={gmName:'name',gmLevel:'level',gmIdentity:'identity',gmTheme:'theme',gmOrigin:'origin',gmPlayerName:'player_name',gmHpCurrent:'hp_current',gmHpMax:'hp_max',gmMpCurrent:'mp_current',gmMpMax:'mp_max',gmIpCurrent:'ip_current',gmIpMax:'ip_max',gmFabulaPoints:'fabula_points',gmClasses:'classes',gmSkills:'skills',gmEquipment:'equipment',gmSpells:'spells',gmBonds:'bonds',gmNotes:'notes'};Object.entries(m).forEach(([id,k])=>els[id].value=c[k]??'');renderGmStatuses();els.gmEditor.classList.remove('hidden');els.gmEditor.scrollIntoView({behavior:'smooth'})}
async function saveGmCharacter(){if(!gmEditingCharacter)return;els.gmSaveStatus.textContent='Saving…';const patch={name:txt('gmName'),level:num('gmLevel'),identity:txt('gmIdentity'),theme:txt('gmTheme'),origin:txt('gmOrigin'),player_name:txt('gmPlayerName'),hp_current:num('gmHpCurrent'),hp_max:num('gmHpMax'),mp_current:num('gmMpCurrent'),mp_max:num('gmMpMax'),ip_current:num('gmIpCurrent'),ip_max:num('gmIpMax'),fabula_points:num('gmFabulaPoints'),classes:txt('gmClasses'),skills:txt('gmSkills'),equipment:txt('gmEquipment'),spells:txt('gmSpells'),bonds:txt('gmBonds'),notes:txt('gmNotes'),statuses:gmEditingStatuses,updated_at:new Date().toISOString()};if(isDemo){Object.assign(state,patch);els.gmSaveStatus.textContent='Saved locally';await loadGMDashboard();return}const {error}=await supabase.from('characters').update(patch).eq('id',gmEditingCharacter.id);els.gmSaveStatus.textContent=error?`Save failed: ${error.message}`:'Saved';if(!error)await loadGMDashboard()}
function addEntry(k,obj){state[k].push(obj);renderStructured();markDirty()}
function wire(){
 els.addClassBtn.onclick=()=>addEntry('classes_struct',{name:'',level:1,benefits:''});els.addSkillBtn.onclick=()=>addEntry('skills_struct',{name:'',rank:1,source:'',effect:''});els.addEquipmentBtn.onclick=()=>addEntry('equipment_struct',{slot:'',name:'',defence:0,magic_defence:0,initiative:0,notes:''});els.addSpellBtn.onclick=()=>addEntry('spells_struct',{name:'',mp:0,targets:'',duration:'',effect:''});els.addBondBtn.onclick=()=>addEntry('bonds_struct',{subject:'',strength:1,feelings:'',notes:''});els.addInventoryBtn.onclick=()=>addEntry('inventory_struct',{name:'',qty:1,notes:''});
 els.authForm.onsubmit=async e=>{e.preventDefault();setAuth('Signing in…');try{await ensureSupabase();const {data,error}=await supabase.auth.signInWithPassword({email:txt('emailInput'),password:els.passwordInput.value});if(error)throw error;currentUser=data.user;setAuth('Loading character…');await enterApp();if(!els.authView.classList.contains('hidden')&&!els.authMessage.textContent.startsWith('Signed in,'))setAuth('')}catch(err){console.error('Sign in failed',err);setAuth(err?.message||'Sign in failed. Please try again.')}};
 els.signUpBtn.onclick=async()=>{setAuth('Creating account…');try{await ensureSupabase();const {error}=await supabase.auth.signUp({email:txt('emailInput'),password:els.passwordInput.value,options:{emailRedirectTo:'https://sladeykins-glitch.github.io/aestra-character-tracker/'}});if(error)throw error;setAuth('Account created. Check your email, then sign in.')}catch(err){setAuth(err?.message||'Could not create account.')}};
 els.demoBtn.onclick=enterDemo;els.logoutBtn.onclick=async()=>{if(supabase)await supabase.auth.signOut();currentUser=null;showAuth()};els.saveBtn.onclick=saveCharacter;els.refreshGmBtn.onclick=loadGMDashboard;els.gmCloseEditor.onclick=()=>els.gmEditor.classList.add('hidden');els.gmSaveBtn.onclick=saveGmCharacter;els.fpMinus.onclick=()=>{state.fabula_points=Math.max(0,state.fabula_points-1);renderDerived();markDirty()};els.fpPlus.onclick=()=>{state.fabula_points++;renderDerived();markDirty()};els.portraitUrl.onchange=()=>{state.portrait_url=txt('portraitUrl');renderPortrait();markDirty()};els.portraitImg.onerror=()=>{els.portraitImg.classList.add('hidden');els.portraitFallback.classList.remove('hidden')};
 document.querySelectorAll('.resource-card').forEach(card=>card.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>{pullForm();const k=`${card.dataset.resource}_current`;state[k]+=Number(b.dataset.delta);renderDerived();markDirty()}));
 ['level','migBase','dexBase','insBase','wlpBase','mig','dex','ins','wlp','hpOther','mpOther','ipOther','initiativeOther','defenceOther','magicDefenceOther'].forEach(id=>els[id]?.addEventListener('change',()=>{pullForm();renderDerived();renderClassSummary();markDirty()}));
 [...document.querySelectorAll('#sheetView input,#sheetView textarea,#sheetView select')].forEach(e=>e.addEventListener('input',()=>{if(!e.closest('.entry-row'))markDirty()}));
 document.querySelectorAll('.tab').forEach(t=>t.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const v=t.dataset.view;els.sheetView.classList.toggle('hidden',v!=='sheet');els.gmView.classList.toggle('hidden',v!=='gm');if(v==='gm')await loadGMDashboard()});
}
try{renderForm();wire();initSupabase()}catch(e){console.error('App startup failed',e);els.connectionBadge.textContent='App error';setAuth(`The tracker hit a startup error: ${e.message||e}`)}