const BUILD_SECTIONS=[
  {key:'classes',label:'Classes',icon:'◆',editor:'classesEditor',add:'addClassBtn',library:'classes',libraryLabel:'Choose Core Class',empty:'No classes selected yet.'},
  {key:'skills',label:'Skills',icon:'✦',editor:'skillsEditor',add:'addSkillBtn',library:'skills',libraryLabel:'Choose Class Skill',empty:'No skills learned yet.'},
  {key:'equipment',label:'Equipment',icon:'◇',editor:'equipmentEditor',add:'addEquipmentBtn',library:'equipment',libraryLabel:'Choose Equipment',empty:'No equipment selected yet.'},
  {key:'magic',label:'Magic',icon:'✧',editor:'spellsEditor',add:'addSpellBtn',library:'spells',libraryLabel:'Choose Spell',empty:'No spells or Arcana learned yet.'}
];

const escBuild=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
let activeBuild='classes';

function sourcePanel(section){return document.getElementById(section.editor)?.closest('article.panel.structured')||null}
function rows(section){return [...(document.getElementById(section.editor)?.querySelectorAll('.entry-row')||[])]}
function values(row){return [...row.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim())}
function summary(section,row){const v=values(row);if(section.key==='classes')return {title:v[0]||'Unnamed Class',meta:`Level ${v[1]||1}`,detail:v[2]||''};if(section.key==='skills')return {title:v[0]||'Unnamed Skill',meta:`${v[2]||'Skill'} · SL ${v[1]||1}`,detail:v[3]||''};if(section.key==='equipment')return {title:v[1]||v[0]||'Unnamed Item',meta:v[0]||'Equipment',detail:[v[5],v[2]&&`DEF ${v[2]}`,v[3]&&`MDEF ${v[3]}`,v[4]&&`INIT ${v[4]}`].filter(Boolean).join(' · ')};return {title:v[0]||'Unnamed Spell',meta:[v[1]&&`${v[1]} MP`,v[2],v[3]].filter(Boolean).join(' · '),detail:v[4]||''}}

function openExisting(section,index){const row=rows(section)[index];if(!row)return;row.classList.add('build-edit-focus');row.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>row.classList.remove('build-edit-focus'),1300)}
function clickCore(mode){const btn=document.querySelector(`[data-core-mode="${mode}"]`);if(btn){btn.click();return true}return false}
function addCustom(section){document.getElementById(section.add)?.click();setTimeout(()=>{const r=rows(section).at(-1);if(r){r.classList.add('build-edit-focus');r.scrollIntoView({behavior:'smooth',block:'center'});r.querySelector('input,textarea,select')?.focus()}},50)}

function renderBuild(){const body=document.getElementById('buildMenuBody');const title=document.getElementById('buildMenuTitle');if(!body)return;const section=BUILD_SECTIONS.find(s=>s.key===activeBuild)||BUILD_SECTIONS[0];title.textContent=section.label;const list=rows(section);body.innerHTML=`<div class="build-actions"><button class="primary build-core-add" type="button">+ ${escBuild(section.libraryLabel)}</button>${section.key==='skills'?'<button class="secondary build-heroic" type="button">Heroic Skills</button>':''}${section.key==='magic'?'<button class="secondary build-arcana" type="button">Arcana</button>':''}<button class="ghost build-custom" type="button">+ Custom / Homebrew</button></div><div class="build-card-list"></div>`;const holder=body.querySelector('.build-card-list');if(!list.length)holder.innerHTML=`<div class="build-empty">${escBuild(section.empty)}<small>Use the button above to add one.</small></div>`;list.forEach((row,i)=>{const s=summary(section,row);const card=document.createElement('button');card.type='button';card.className=`build-entry build-entry-${section.key}`;card.innerHTML=`<span class="build-entry-glyph">${section.icon}</span><span class="build-entry-copy"><strong>${escBuild(s.title)}</strong><small>${escBuild(s.meta)}</small>${s.detail?`<span>${escBuild(s.detail)}</span>`:''}</span><span class="build-entry-arrow">›</span>`;card.onclick=()=>openExisting(section,i);holder.appendChild(card)});body.querySelector('.build-core-add').onclick=()=>{if(!clickCore(section.library))addCustom(section)};body.querySelector('.build-custom').onclick=()=>addCustom(section);body.querySelector('.build-heroic')?.addEventListener('click',()=>clickCore('heroics'));body.querySelector('.build-arcana')?.addEventListener('click',()=>clickCore('arcana'));document.querySelectorAll('.build-tab').forEach(b=>b.classList.toggle('active',b.dataset.build===activeBuild))}

function installBuildMenu(){if(document.getElementById('buildMenu'))return;const first=sourcePanel(BUILD_SECTIONS[0]);if(!first)return;const menu=document.createElement('article');menu.id='buildMenu';menu.className='panel build-menu';menu.innerHTML=`<div class="build-menu-head"><div><p class="eyebrow">Character Menu</p><h3>Build & Abilities</h3></div><span class="build-menu-hint">Tap an entry to inspect or edit</span></div><div class="build-tabs">${BUILD_SECTIONS.map(s=>`<button type="button" class="build-tab${s.key===activeBuild?' active':''}" data-build="${s.key}"><span>${s.icon}</span>${s.label}</button>`).join('')}</div><div class="build-page-head"><button type="button" class="build-cycle" data-dir="-1">‹</button><h4 id="buildMenuTitle">Classes</h4><button type="button" class="build-cycle" data-dir="1">›</button></div><div id="buildMenuBody"></div>`;first.before(menu);BUILD_SECTIONS.forEach(s=>{const p=sourcePanel(s);if(p)p.classList.add('build-source-panel')});menu.querySelectorAll('.build-tab').forEach(b=>b.onclick=()=>{activeBuild=b.dataset.build;renderBuild()});menu.querySelectorAll('.build-cycle').forEach(b=>b.onclick=()=>{const i=BUILD_SECTIONS.findIndex(s=>s.key===activeBuild);activeBuild=BUILD_SECTIONS[(i+Number(b.dataset.dir)+BUILD_SECTIONS.length)%BUILD_SECTIONS.length].key;renderBuild()});BUILD_SECTIONS.forEach(s=>document.getElementById(s.editor)?.addEventListener('input',()=>requestAnimationFrame(renderBuild)));const observer=new MutationObserver(()=>requestAnimationFrame(renderBuild));BUILD_SECTIONS.forEach(s=>{const e=document.getElementById(s.editor);if(e)observer.observe(e,{childList:true})});renderBuild();
const style=document.createElement('style');style.textContent=`
.build-source-panel{position:absolute!important;left:-10000px!important;width:1px!important;height:1px!important;overflow:hidden!important;opacity:0!important;pointer-events:none!important}
.build-menu{overflow:hidden;position:relative}.build-menu:before{content:'';position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 0,rgba(118,191,255,.07),transparent 45%)}
.build-menu-head{display:flex;justify-content:space-between;gap:12px;align-items:end;margin-bottom:12px}.build-menu-head h3{margin:.1rem 0 0;font-size:1.45rem}.build-menu-hint{font-size:.78rem;opacity:.58}
.build-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;padding:5px;border:1px solid rgba(216,177,96,.25);border-radius:14px;background:rgba(0,0,0,.24)}.build-tab{border:0!important;background:transparent!important;min-height:48px;border-radius:10px!important;display:flex;gap:6px;align-items:center;justify-content:center;color:inherit!important;opacity:.62}.build-tab span{color:#d8b160}.build-tab.active{opacity:1;background:linear-gradient(180deg,rgba(83,137,175,.2),rgba(216,177,96,.08))!important;box-shadow:inset 0 0 0 1px rgba(216,177,96,.3),0 0 18px rgba(75,150,220,.08)}
.build-page-head{display:grid;grid-template-columns:42px 1fr 42px;align-items:center;margin:13px 0 9px;text-align:center}.build-page-head h4{margin:0;text-transform:uppercase;letter-spacing:.18em;font-size:.84rem;color:#e2c783}.build-cycle{font-size:1.45rem;padding:4px!important;background:transparent!important;border:0!important;color:#d8b160!important}.build-actions{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px}.build-actions button{font-size:.8rem}.build-card-list{display:grid;gap:8px}.build-entry{width:100%;display:grid!important;grid-template-columns:34px 1fr 20px;gap:10px;align-items:center;text-align:left!important;padding:11px 12px!important;border:1px solid rgba(216,177,96,.22)!important;border-radius:12px!important;background:linear-gradient(100deg,rgba(18,24,31,.86),rgba(30,24,29,.76))!important;color:inherit!important;transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease}.build-entry:hover{transform:translateY(-1px);border-color:rgba(216,177,96,.5)!important;box-shadow:0 0 18px rgba(79,147,214,.09)}.build-entry-glyph{font-size:1.15rem;color:#d8b160;text-align:center;text-shadow:0 0 10px rgba(117,189,255,.4)}.build-entry-copy{display:grid;gap:2px;min-width:0}.build-entry-copy strong{font-size:.98rem}.build-entry-copy small{font-size:.73rem;color:#d8b160;opacity:.82}.build-entry-copy>span{font-size:.76rem;opacity:.62;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.build-entry-arrow{font-size:1.35rem;opacity:.48}.build-entry-magic .build-entry-glyph{color:#8bc8ff}.build-entry-equipment .build-entry-glyph{color:#d9c48b}.build-empty{padding:25px 12px;text-align:center;border:1px dashed rgba(216,177,96,.2);border-radius:12px;opacity:.65}.build-empty small{display:block;margin-top:4px}.build-edit-focus{outline:2px solid rgba(129,198,255,.75)!important;box-shadow:0 0 28px rgba(94,174,255,.28)!important}
@media(max-width:640px){.build-menu-head{align-items:start}.build-menu-hint{display:none}.build-tabs{gap:3px}.build-tab{font-size:.69rem;min-height:44px;flex-direction:column;gap:1px}.build-tab span{font-size:.9rem}.build-actions{display:grid;grid-template-columns:1fr 1fr}.build-actions .build-core-add{grid-column:1/-1}.build-entry{padding:10px!important}}
`;document.head.appendChild(style)}

setTimeout(installBuildMenu,0);
