const normClass=v=>String(v||'').trim().toLowerCase();
function classLevels(){const map=new Map();document.querySelectorAll('#classesEditor .entry-row').forEach(row=>{const inputs=row.querySelectorAll('input,textarea,select');const name=String(inputs[0]?.value||'').trim(),level=Number(inputs[1]?.value)||0;if(name)map.set(normClass(name),level)});return map}
function decorateClassMastery(){const levels=classLevels();document.querySelectorAll('#buildMenuBody .build-entry-classes').forEach(card=>{const name=card.querySelector('.build-entry-copy strong')?.textContent||'';const mastered=(levels.get(normClass(name))||0)>=10;card.classList.toggle('class-mastered',mastered);const copy=card.querySelector('.build-entry-copy');let badge=copy?.querySelector('.class-mastered-badge');if(mastered&&!badge){badge=document.createElement('small');badge.className='class-mastered-badge';badge.textContent='MASTERED';copy?.appendChild(badge)}else if(!mastered&&badge)badge.remove()})}
function decorateOpenClass(card){if(!card.classList.contains('build-entry-classes'))return;setTimeout(()=>{const modal=document.getElementById('buildDetailModal');const icon=modal?.querySelector('.build-detail-icon');if(!icon)return;const mastered=card.classList.contains('class-mastered');icon.classList.toggle('class-mastered-icon',mastered);if(mastered){let badge=modal.querySelector('.class-mastered-modal-badge');if(!badge){badge=document.createElement('span');badge.className='class-mastered-modal-badge';badge.textContent='MASTERED CLASS';modal.querySelector('.build-detail-heading>div')?.appendChild(badge)}}else modal.querySelector('.class-mastered-modal-badge')?.remove()},0)}
function installClassMastery(){if(document.getElementById('classMasteryStyles'))return;const style=document.createElement('style');style.id='classMasteryStyles';style.textContent=`
.build-entry-classes.class-mastered{border-color:rgba(239,205,105,.72)!important;background:linear-gradient(100deg,rgba(30,27,18,.94),rgba(35,25,37,.84))!important;box-shadow:inset 0 0 18px rgba(240,202,91,.08),0 0 20px rgba(228,184,69,.11)!important}.build-entry-classes.class-mastered .build-entry-glyph{position:relative;color:#f1cf68!important;filter:drop-shadow(0 0 8px rgba(255,211,92,.55))}.build-entry-classes.class-mastered .build-entry-glyph:before{content:'';position:absolute;inset:-7px;border:1px solid rgba(245,211,112,.72);transform:rotate(45deg);box-shadow:0 0 12px rgba(236,191,71,.28),inset 0 0 8px rgba(236,191,71,.1)}.build-entry-classes.class-mastered .build-entry-glyph:after{content:'✦';position:absolute;right:-9px;top:-12px;font-size:.7rem;color:#fff0a8;text-shadow:0 0 8px #ffd866;transform:none}.class-mastered-badge{width:max-content;margin-top:3px;padding:2px 6px;border:1px solid rgba(235,196,84,.42);border-radius:999px;color:#f3d77a!important;background:rgba(111,82,18,.16);font-size:.6rem!important;letter-spacing:.12em!important;opacity:.95!important}.class-mastered-icon{border-color:rgba(244,208,101,.82)!important;box-shadow:0 0 24px rgba(239,196,72,.3),inset 0 0 14px rgba(239,196,72,.12)!important}.class-mastered-icon:after{content:'✦';position:absolute;right:-8px;top:-10px;color:#ffe895;font-size:.78rem;text-shadow:0 0 10px #ffd65d}.class-mastered-modal-badge{display:inline-block;margin-top:7px;padding:3px 8px;border-radius:999px;border:1px solid rgba(235,196,84,.45);color:#f0d376;background:rgba(107,79,16,.18);font-size:.64rem;letter-spacing:.14em}
`;
document.head.appendChild(style);decorateClassMastery();document.getElementById('classesEditor')?.addEventListener('input',()=>requestAnimationFrame(decorateClassMastery));const body=document.getElementById('buildMenuBody');if(body)new MutationObserver(()=>requestAnimationFrame(decorateClassMastery)).observe(body,{childList:true,subtree:false});document.addEventListener('click',e=>{const card=e.target.closest?.('#buildMenuBody .build-entry-classes');if(card)decorateOpenClass(card)},true)}
setTimeout(installClassMastery,0);
