// High Fantasy custom weapons — rule-driven builder, loadout integration, and transforming forms.
(function(){
  const $=id=>document.getElementById(id), norm=v=>String(v||'').trim().toLowerCase(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const EQ='§AESTRAEQ:', CW='§AESTRACW:';
  const cats=['arcane','bow','brawling','dagger','firearm','flail','heavy','spear','sword','thrown'];
  const elements=['air','bolt','dark','earth','fire','ice','light','poison'];
  const customs={
    accurate:{name:'Accurate',weight:1,martial:false,desc:'Adds +2 to the weapon’s Accuracy Check.'},
    defense:{name:'Defense Boost',weight:1,martial:false,desc:'Gain +2 Defense; for Skills, treat the wielder as having a shield equipped.'},
    elemental:{name:'Elemental',weight:1,martial:false,desc:'Choose a damage type; the weapon deals that type instead of physical and deals 2 extra damage.'},
    mdef:{name:'Magic Defense Boost',weight:1,martial:true,desc:'Gain +2 Magic Defense.'},
    powerful:{name:'Powerful',weight:1,martial:true,desc:'Deal 5 extra damage, or 7 extra damage if heavy. Not available to arcane/dagger weapons or with Quick.'},
    quick:{name:'Quick',weight:2,martial:true,desc:'Counts as two customizations. Attack twice when using the Attack action; both attacks follow two-weapon fighting rules.'},
    transforming:{name:'Transforming',weight:1,martial:false,desc:'Adds 100z to the weapon cost. Design a second form; switch forms once per turn during conflicts when no other effect is resolving.'}
  };
  const enc=o=>{try{const b=new TextEncoder().encode(JSON.stringify(o));let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}catch{return''}}, dec=s=>{try{const b=atob(s),u=Uint8Array.from(b,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(u))}catch{return null}};
  const fields=r=>[...r.querySelectorAll('input,textarea,select')], rows=()=>[...($('equipmentEditor')?.querySelectorAll('.entry-row')||[])];
  function eqMeta(notes){const m=String(notes||'').match(/§AESTRAEQ:([A-Za-z0-9+/=]+)/);return m?dec(m[1]):null}
  function effective(row){const f=fields(row),raw={slot:f[0]?.value||'',name:f[1]?.value||'',def:Number(f[2]?.value)||0,mdef:Number(f[3]?.value)||0,init:Number(f[4]?.value)||0,notes:f[5]?.value||''},m=eqMeta(raw.notes);return m?{...raw,slot:m.slot||'',def:Number(m.def)||0,mdef:Number(m.mdef)||0,init:Number(m.init)||0,notes:m.notes||'',stowed:true}:{...raw,stowed:false}}
  function cwMeta(notes){const m=String(notes||'').match(/§AESTRACW:([A-Za-z0-9+/=]+)/);return m?dec(m[1]):null}
  function set(el,v){if(!el)return;el.value=String(v??'');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
  function formStats(form){const list=form.customs||[],cat=form.category;let plus=5,type='physical',acc='';if(list.includes('elemental')){plus+=2;type=form.element||'fire'}if(list.includes('powerful'))plus+=cat==='heavy'?7:5;if(list.includes('accurate'))acc=' +2';return{def:list.includes('defense')?2:0,mdef:list.includes('mdef')?2:0,damage:`【HR + ${plus}】 ${type}`,accuracy:`${form.accuracy}${acc}`,martial:list.some(k=>customs[k]?.martial)}}
  function formSummary(form,label){const s=formStats(form),names=(form.customs||[]).map(k=>customs[k]?.name+(k==='elemental'?` (${form.element})`:''));return `${label} — ${form.category} · ${form.range} · Two-handed · ${s.martial?'Martial':'Non-martial'}\nAccuracy ${s.accuracy}\nDamage ${s.damage}\nCustomizations: ${names.join(' · ')}`}
  function buildNotes(meta){const i=meta.active||0,f=meta.forms[i],other=meta.forms[1-i],s=formStats(f),lines=[`[Custom Weapon] High Fantasy · p. 106–108`,formSummary(f,meta.forms.length>1?`Active Form ${i+1}`:'Weapon')];if((f.customs||[]).includes('defense'))lines.push('Defense Boost: +2 DEF; counts as protective equipment for relevant Skills.');if((f.customs||[]).includes('mdef'))lines.push('Magic Defense Boost: +2 MDEF.');if((f.customs||[]).includes('quick'))lines.push('Quick: with the Attack action, you may make two attacks; both follow two-weapon fighting rules.');if((f.customs||[]).includes('transforming')&&other){lines.push(`Transforming: switch forms once per turn during a conflict, while no other effect is resolving.`);lines.push(formSummary(other,`Other Form ${1-i+1}`))}lines.push(`Cost ${meta.cost}z`);lines.push(`${CW}${enc(meta)}`);return lines.join('\n')}
  function stowNew(row,meta){const f=fields(row),s=formStats(meta.forms[meta.active||0]),notes=buildNotes(meta),packed=enc({slot:'Two hands',def:s.def,mdef:s.mdef,init:0,notes});set(f[0],'Loadout');set(f[1],meta.name);set(f[2],0);set(f[3],0);set(f[4],0);set(f[5],`Stored in loadout\n${EQ}${packed}`);document.dispatchEvent(new CustomEvent('aestra:equipment-changed'))}
  function writeActive(row,meta){const f=fields(row),e=effective(row),s=formStats(meta.forms[meta.active||0]),notes=buildNotes(meta);if(e.stowed){set(f[5],`Stored in loadout\n${EQ}${enc({slot:'Two hands',def:s.def,mdef:s.mdef,init:0,notes})}`)}else{set(f[0],'Two hands');set(f[2],s.def);set(f[3],s.mdef);set(f[4],0);set(f[5],notes)}document.dispatchEvent(new CustomEvent('aestra:equipment-changed'))}
  const zenit=()=>Math.max(0,Number($('zenit')?.value)||0);function spend(n){const z=$('zenit');if(!z)return;set(z,Math.max(0,zenit()-n));document.dispatchEvent(new CustomEvent('aestra:zenit-changed',{detail:{zenit:Number(z.value)||0}}))}
  function toast(t){let x=$('customWeaponToast');if(!x){x=document.createElement('div');x.id='customWeaponToast';x.className='cw-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)}
  function modal(){let m=$('customWeaponModal');if(m)return m;m=document.createElement('div');m.id='customWeaponModal';m.className='cw-modal hidden';m.innerHTML='<div class="cw-dialog"><button class="cw-close" type="button">×</button><div id="cwBody"></div></div>';document.body.appendChild(m);m.querySelector('.cw-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
  function formHtml(n,second=false){return `<section class="cw-form" data-cw-form="${n}"><h3>${second?'Form II':'Form I'}</h3><div class="cw-fields"><label>Category<select data-cw-category>${cats.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Range<select data-cw-range><option>Melee</option><option>Ranged</option></select></label><label>Accuracy<select data-cw-accuracy><option>【DEX + INS】</option><option>【DEX + MIG】</option></select></label>${second?'<input type="hidden" data-cw-transforming value="1">':''}</div><div class="cw-customs">${Object.entries(customs).filter(([k])=>!(second&&k==='transforming')).map(([k,c])=>`<label data-cw-choice="${k}"><input type="checkbox" value="${k}"><span><strong>${c.name}${c.martial?' · Martial':''}${c.weight===2?' · counts as 2':''}</strong><small>${esc(c.desc)}</small></span></label>`).join('')}</div><label class="cw-element hidden">Element<select data-cw-element>${elements.map(x=>`<option>${x}</option>`).join('')}</select></label><div class="cw-points"><span>Customizations</span><strong data-cw-points>0 / 3</strong></div></section>`}
  function formData(sec,forceTransform=false){const checked=[...sec.querySelectorAll('.cw-customs input:checked')].map(x=>x.value);if(forceTransform)checked.unshift('transforming');return{category:sec.querySelector('[data-cw-category]').value,range:sec.querySelector('[data-cw-range]').value,accuracy:sec.querySelector('[data-cw-accuracy]').value,customs:checked,element:sec.querySelector('[data-cw-element]')?.value||'fire'}}
  function points(form){return(form.customs||[]).reduce((a,k)=>a+(customs[k]?.weight||0),0)}
  function refreshBuilder(){const b=$('cwBody');if(!b)return;const one=b.querySelector('[data-cw-form="1"]'),f1=formData(one),hasT=f1.customs.includes('transforming');let two=b.querySelector('[data-cw-form="2"]');if(hasT&&!two){one.insertAdjacentHTML('afterend',formHtml(2,true));two=b.querySelector('[data-cw-form="2"]');bindForm(two);two.querySelector('[data-cw-category]').value=one.querySelector('[data-cw-category]').value}if(!hasT&&two)two.remove();[...b.querySelectorAll('.cw-form')].forEach((sec,i)=>{const f=formData(sec,i===1),p=points(f),pout=sec.querySelector('[data-cw-points]');pout.textContent=`${p} / 3`;pout.classList.toggle('bad',p>3);sec.querySelector('.cw-element')?.classList.toggle('hidden',!f.customs.includes('elemental'));sec.querySelectorAll('.cw-customs input').forEach(x=>{if(x.checked)return;const key=x.value,next={...f,customs:[...f.customs,key]};let bad=points(next)>3;if(key==='powerful'&&(f.category==='arcane'||f.category==='dagger'||f.customs.includes('quick')))bad=true;if(key==='quick'&&f.customs.includes('powerful'))bad=true;x.disabled=bad});const pow=sec.querySelector('input[value="powerful"]');if(pow&&pow.checked&&(f.category==='arcane'||f.category==='dagger'||f.customs.includes('quick'))){pow.checked=false;refreshBuilder()}});const forms=[...b.querySelectorAll('.cw-form')].map((s,i)=>formData(s,i===1)),valid=forms.every(f=>points(f)===3)&&(!forms[0].customs.includes('transforming')||forms.length===2);const cost=300+(forms[0].customs.includes('transforming')?100:0);b.querySelector('[data-cw-cost]').textContent=`${cost}z`;const buy=b.querySelector('[data-cw-buy]');buy.disabled=!valid||cost>zenit();buy.textContent=cost>zenit()?`Need ${cost-zenit()}z more`:`Buy & add · ${cost}z`;b.querySelector('[data-cw-free]').disabled=!valid}
  function bindForm(sec){sec.addEventListener('change',refreshBuilder)}
  function openBuilder(){const m=modal(),b=$('cwBody');b.innerHTML=`<p class="eyebrow">High Fantasy · Custom Weapons</p><h2>Create Custom Weapon</h2><p class="cw-help">All custom weapons are two-handed, cost 300z, use 【DEX + INS】 or 【DEX + MIG】, deal 【HR + 5】 physical damage, and receive exactly three customizations.</p><label>Weapon name<input id="cwName" placeholder="e.g. Orchestral Claymore"></label>${formHtml(1)}<div class="cw-summary"><span>Total cost</span><strong data-cw-cost>300z</strong></div><div class="cw-actions"><button class="primary" data-cw-buy type="button">Buy & add</button><button class="ghost" data-cw-free type="button">Add without gold</button></div>`;bindForm(b.querySelector('[data-cw-form="1"]'));const finish=pay=>{const name=$('cwName').value.trim();if(!name){toast('Give the weapon a name first.');return}const secs=[...b.querySelectorAll('.cw-form')],forms=secs.map((s,i)=>formData(s,i===1));if(!forms.every(f=>points(f)===3)){toast('Each form must use exactly 3 customization points.');return}const cost=300+(forms[0].customs.includes('transforming')?100:0);if(pay&&cost>zenit()){toast('Not enough Zenit.');return}if(pay)spend(cost);const meta={name,cost,active:0,forms};$('addEquipmentBtn')?.click();requestAnimationFrame(()=>{const row=rows().at(-1);if(!row){toast('Could not add the weapon.');return}stowNew(row,meta);m.classList.add('hidden');toast(`${name} added to your loadout.`);setTimeout(decorateTransformButtons,80)})};b.querySelector('[data-cw-buy]').onclick=()=>finish(true);b.querySelector('[data-cw-free]').onclick=()=>finish(false);refreshBuilder();m.classList.remove('hidden')}
  function installButton(){const actions=document.querySelector('#equipmentWorkbench .equipment-shop-actions');if(!actions||$('createCustomWeaponBtn'))return;const b=document.createElement('button');b.id='createCustomWeaponBtn';b.type='button';b.className='secondary';b.textContent='Create Custom Weapon';b.onclick=openBuilder;actions.appendChild(b)}
  function decorateTransformButtons(){const list=document.querySelector('#equipmentWorkbench .equip-loadout-list');if(!list)return;list.querySelectorAll('.cw-transform-control').forEach(x=>x.remove());list.querySelectorAll('.equip-pool-card[data-equip-index]').forEach(card=>{const i=Number(card.dataset.equipIndex),row=rows()[i];if(!row)return;const m=cwMeta(effective(row).notes);if(!m||!Array.isArray(m.forms)||m.forms.length<2)return;const b=document.createElement('button');b.type='button';b.className='cw-transform-control';b.textContent=`Transform → Form ${(m.active||0)===0?2:1}`;b.onclick=e=>{e.preventDefault();e.stopPropagation();const fresh=cwMeta(effective(row).notes);if(!fresh)return;fresh.active=(fresh.active||0)===0?1:0;writeActive(row,fresh);toast(`${fresh.name} changed to Form ${fresh.active+1}.`);setTimeout(decorateTransformButtons,60)};card.insertAdjacentElement('afterend',b)})}
  function defenseBoostFix(){const equipped=rows().some(r=>{const e=effective(r),m=cwMeta(e.notes);return !e.stowed&&m?.forms?.[m.active||0]?.customs?.includes('defense')});if(!equipped)return;const dodge=rowsSkills().filter(x=>norm(x.name)==='dodge').reduce((a,x)=>a+x.rank,0);if(!dodge)return;requestAnimationFrame(()=>{const d=$('defenceText');if(!d)return;const val=Number(d.textContent);if(Number.isFinite(val))d.textContent=String(val-dodge)})}
  function rowsSkills(){return [...($('skillsEditor')?.querySelectorAll('.entry-row')||[])].map(r=>{const f=fields(r);return{name:f[0]?.value||'',rank:Number(f[1]?.value)||0}})}
  const style=document.createElement('style');style.textContent=`.cw-modal{position:fixed;inset:0;z-index:2400;display:grid;place-items:center;padding:14px;background:rgba(2,4,8,.88)}.cw-modal.hidden{display:none!important}.cw-dialog{position:relative;width:min(930px,97vw);max-height:92vh;overflow:auto;padding:24px;border:1px solid rgba(211,171,91,.42);border-radius:18px;background:linear-gradient(145deg,#10151d,#19141b)}.cw-close{position:absolute!important;right:11px;top:11px;width:36px!important;height:36px!important;min-height:0!important;padding:0!important;border-radius:50%!important}.cw-help{max-width:760px;font-size:.76rem;line-height:1.5;color:#aaa08d}.cw-form{margin-top:15px;padding:13px;border:1px solid rgba(211,171,91,.2);border-radius:13px;background:rgba(255,255,255,.02)}.cw-form h3{margin:0 0 10px;color:#e4ce9c}.cw-fields{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.cw-customs{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.cw-customs label{display:flex!important;gap:8px;align-items:flex-start;padding:9px;border:1px solid rgba(211,171,91,.16);border-radius:9px}.cw-customs span{display:grid;gap:2px}.cw-customs small{font-size:.65rem;line-height:1.35;opacity:.7}.cw-element{margin-top:9px}.cw-points,.cw-summary{display:flex;justify-content:space-between;align-items:center;margin-top:10px;padding-top:9px;border-top:1px solid rgba(211,171,91,.1)}.cw-points .bad{color:#ef8f8f}.cw-actions{display:flex;gap:8px;margin-top:13px}.cw-transform-control{display:block!important;width:auto!important;margin:-2px 8px 7px auto!important;min-height:28px!important;padding:4px 9px!important;border-radius:999px!important;font-size:.58rem!important;color:#cbb3e8!important;border-color:rgba(167,132,210,.3)!important;background:rgba(92,59,122,.13)!important}.cw-toast{position:fixed;left:50%;bottom:78px;z-index:2500;transform:translate(-50%,8px);opacity:0;pointer-events:none;padding:8px 12px;border:1px solid rgba(211,171,91,.3);border-radius:999px;background:#111015;color:#e6d7b5;font-size:.72rem;transition:.15s}.cw-toast.show{opacity:1;transform:translate(-50%,0)}@media(max-width:640px){#createCustomWeaponBtn{width:100%!important}.cw-fields,.cw-customs{grid-template-columns:1fr}.cw-actions{display:grid}.cw-dialog{padding:18px 14px}}`;document.head.appendChild(style);
  function boot(){installButton();decorateTransformButtons();const work=$('equipmentWorkbench');if(!work){setTimeout(boot,120);return}new MutationObserver(()=>{requestAnimationFrame(()=>{installButton();decorateTransformButtons();defenseBoostFix()})}).observe(work,{childList:true,subtree:true});$('equipmentEditor')?.addEventListener('input',()=>setTimeout(()=>{decorateTransformButtons();defenseBoostFix()},0));$('skillsEditor')?.addEventListener('input',()=>setTimeout(defenseBoostFix,0));document.addEventListener('aestra:equipment-changed',()=>setTimeout(()=>{decorateTransformButtons();defenseBoostFix()},0));}
  boot();
})();