// Techno Fantasy Esper — Psychic Gifts, focus reference and Brainwave Clock.
(function(){
 const CONFIG=window.AESTRA_CONFIG||{},norm=v=>String(v||'').trim().toLowerCase(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rows=id=>[...(document.getElementById(id)?.querySelectorAll('.entry-row')||[])],vals=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
 const GIFTS={
 'Atmokinesis':{event:'When you deal damage',effect:'Damage becomes air or bolt; source gains extra damage equal to 2 + filled Brainwave sections.'},
 'Clairvoyance':{event:'When an NPC becomes your focus or you create a Bond toward an NPC',effect:'Ask the GM one truthful question about that NPC; once per NPC.'},
 'Gravitokinesis':{event:'When you deal damage',effect:'Damage becomes earth or physical; source gains extra damage equal to 2 + filled sections. Damaged flying creatures are forced to land.'},
 'Life Transference':{event:'When you cause enemies to lose HP',effect:'Choose yourself or your focused ally; if in Crisis, recover 5 + (filled sections × 5) HP.'},
 'Photokinesis':{event:'When you deal damage',effect:'Damage becomes dark or light; source gains extra damage equal to 2 + filled sections.'},
 'Psychic Backlash':{event:'After an enemy succeeds on an Opposed Check against you or causes you to lose HP',effect:'Enemy loses 5 + (filled sections × 5) MP, then suffers dazed or shaken.'},
 'Psychic Shield':{event:'After a visible enemy performs an Accuracy or Magic Check',effect:'For that Check, Defense and Magic Defense may equal current WLP die size + (filled sections × 2), if better.'},
 'Reassuring Presence':{event:'After you cover an ally with Guard',effect:'That ally recovers 10 + (filled sections × 5) MP; if they are your focus, they also recover from dazed, enraged, or shaken.'},
 'Thermokinesis':{event:'When you deal damage',effect:'Damage becomes fire or ice; source gains extra damage equal to 2 + filled sections.'}
 };
 let sb=null,charId=null,state={gifts:[],clock:0};
 const present=()=>rows('classesEditor').some(r=>norm(vals(r)[0])==='esper');
 const rank=n=>rows('skillsEditor').map(r=>{const v=vals(r);return{name:v[0],rank:+v[1]||0,source:v[2]}}).find(x=>norm(x.name)===norm(n)&&norm(x.source).includes('esper'))?.rank||0;
 const heroic=n=>rows('skillsEditor').some(r=>norm(vals(r)[0])===norm(n));
 async function client(){if(sb)return sb;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=m.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);return sb}
 async function resolve(){const c=await client(),{data:{user}}=await c.auth.getUser();if(!user)return null;const name=document.getElementById('charName')?.value?.trim();if(!name)return null;const {data}=await c.from('characters').select('id,esper_options,updated_at').eq('owner_id',user.id).eq('campaign_id',CONFIG.campaignId).eq('name',name).order('updated_at',{ascending:false}).limit(1);return data?.[0]||null}
 function clean(o={}){const max=rank('Psychic Gifts');return{gifts:Array.isArray(o.gifts)?o.gifts.filter(x=>GIFTS[x]).slice(0,max):[],clock:Math.max(0,Math.min(4,+o.clock||0))}}
 async function load(){const r=await resolve().catch(()=>null);if(r){charId=r.id;state=clean(r.esper_options||{})}renderAll()}
 async function save(){state=clean(state);if(!charId)charId=(await resolve().catch(()=>null))?.id||null;if(!charId)return;const c=await client();await c.from('characters').update({esper_options:state,updated_at:new Date().toISOString()}).eq('id',charId).eq('campaign_id',CONFIG.campaignId)}
 function modal(){let m=document.getElementById('esperModal');if(m)return m;m=document.createElement('div');m.id='esperModal';m.className='es-modal hidden';m.innerHTML='<div class="es-dialog"><button class="es-close">×</button><div id="esBody"></div></div>';document.body.appendChild(m);m.querySelector('.es-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
 function cost(){return Math.max(5,state.clock*5)}
 function effectText(g){return GIFTS[g].effect.replaceAll('filled sections',String(state.clock))}
 function configure(){const m=modal(),b=document.getElementById('esBody'),max=rank('Psychic Gifts');b.innerHTML=`<p class="eyebrow">Techno Fantasy · Esper</p><h2>Psychic Gifts</h2><p class="es-help">Psychic Gifts SL ${max}: learn exactly one gift per Skill Level.</p><div class="es-gifts">${Object.entries(GIFTS).map(([n,g])=>`<label class="${state.gifts.includes(n)?'active':''}"><input type="checkbox" value="${esc(n)}" ${state.gifts.includes(n)?'checked':''} ${!state.gifts.includes(n)&&state.gifts.length>=max?'disabled':''}><span><strong>${esc(n)}</strong><small>${esc(g.event)}</small><p>${esc(g.effect)}</p></span></label>`).join('')}</div><p class="es-count">${state.gifts.length} / ${max} learned</p>`;b.querySelectorAll('input[type=checkbox]').forEach(x=>x.onchange=()=>{if(x.checked&&state.gifts.length<max)state.gifts.push(x.value);else if(!x.checked)state.gifts=state.gifts.filter(v=>v!==x.value);save();configure();renderAll()});m.classList.remove('hidden')}
 function useGift(g){if(!state.gifts.includes(g))return;const before=state.clock,mp=Math.max(5,before*5),extra=(document.getElementById('level')?.value>=40?20:document.getElementById('level')?.value>=20?10:0);alert(`${g}\nCost: ${mp} MP\n${effectText(g)}${extra&&/(recover|loses)/i.test(GIFTS[g].effect)?`\nLevel scaling: HP/MP recovery or MP loss increases by ${extra}.`:''}`);state.clock=Math.min(4,state.clock+1);save();open();renderAll()}
 function open(){const m=modal(),b=document.getElementById('esBody');b.innerHTML=`<p class="eyebrow">Techno Fantasy · Esper</p><h2>Brainwave Chamber</h2><div class="es-clock"><div class="es-ring">${[0,1,2,3].map(i=>`<i class="${i<state.clock?'on':''}" style="--i:${i}"></i>`).join('')}<strong>${state.clock}/4</strong></div><div><b>Current Gift cost: ${cost()} MP</b><small>After resolving a gift, fill 1 section. The Clock begins each scene empty.</small><button id="esReset" class="ghost">New Scene · Empty Clock</button></div></div><div class="es-focus"><b>Cognitive Focus</b><span>At turn start, choose an audible ally or a visible enemy with dazed/enraged/shaken. Cognitive Focus and Hypercognition scale from this target.</span></div><div class="es-grid">${state.gifts.map(g=>`<article><span>${esc(GIFTS[g].event)}</span><strong>${esc(g)}</strong><p>${esc(effectText(g))}</p><button data-gift="${esc(g)}">Use Gift · ${cost()} MP</button></article>`).join('')||'<p class="muted">Learn Psychic Gifts to populate this chamber.</p>'}</div>${heroic('Brainwave Discharge')?`<div class="es-hero"><b>Brainwave Discharge</b><span>${state.clock===4?'Clock full: action available now.':'Requires a full 4/4 Brainwave Clock.'}</span>${state.clock===4?'<button id="esDischarge">Discharge & empty clock</button>':''}</div>`:''}${heroic('Psychic Field')?'<div class="es-hero"><b>Psychic Field</b><span>Damage-trigger gifts may also trigger from audible allies; Psychic Shield extends to audible allies.</span></div>':''}<button id="esConfigure" class="secondary">Configure Learned Gifts</button>`;b.querySelector('#esReset').onclick=()=>{state.clock=0;save();open();renderAll()};b.querySelector('#esConfigure').onclick=configure;b.querySelectorAll('[data-gift]').forEach(x=>x.onclick=()=>useGift(x.dataset.gift));b.querySelector('#esDischarge')?.addEventListener('click',()=>{state.clock=0;save();open();renderAll()});m.classList.remove('hidden')}
 function renderBuild(){const old=document.querySelector('.esper-build-tools');if(!present()){old?.remove();return}const body=document.getElementById('buildMenuBody');if(!body)return;const sec=document.querySelector('.build-tab.active')?.dataset.build;if(!['classes','skills'].includes(sec)){old?.remove();return}let box=old;if(!box){box=document.createElement('section');box.className='esper-build-tools';(document.getElementById('classHierarchy')||body.querySelector('.build-actions'))?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<div><p class="eyebrow">Techno Fantasy · Esper</p><strong>Brainwave Chamber</strong><small>${state.gifts.length}/${rank('Psychic Gifts')} gifts · Brainwave ${state.clock}/4 · ${cost()} MP current cost</small></div><button class="secondary">Open Psychic Tools</button>`;box.querySelector('button').onclick=open}
 function inject(){const host=document.getElementById('sessionActionBody');if(!host)return;const old=host.querySelector('[data-esper-action]'),mode=host.dataset.mode;if(!present()||!rank('Psychic Gifts')||!['skills','favourites'].includes(mode)){old?.remove();return}if(old)return;const c=document.createElement('article');c.className='a2-card';c.dataset.esperAction='1';c.innerHTML=`<button class="a2-open"><span class="a2-kind">◈ SKILL · ESPER</span><strong>Psychic Gifts</strong><small>Brainwave ${state.clock}/4 · ${cost()} MP</small><p>React to events with learned gifts; resolving one fills the Brainwave Clock.</p><span class="a2-more">Open chamber ›</span></button>`;c.querySelector('button').onclick=e=>{e.stopPropagation();open()};host.prepend(c)}
 function renderAll(){state=clean(state);renderBuild();inject()}
 const st=document.createElement('style');st.textContent=`.esper-build-tools{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:10px;padding:12px;border:1px solid rgba(93,191,200,.3);border-radius:12px;background:linear-gradient(110deg,rgba(44,126,135,.13),rgba(139,77,159,.08))}.esper-build-tools>div{display:grid;gap:3px}.esper-build-tools .eyebrow{margin:0}.esper-build-tools small{opacity:.7}.es-modal{position:fixed;inset:0;z-index:2390;display:grid;place-items:center;padding:14px;background:rgba(4,7,12,.91)}.es-modal.hidden{display:none!important}.es-dialog{position:relative;width:min(980px,96vw);max-height:93vh;overflow:auto;padding:24px;border:1px solid rgba(91,196,210,.4);border-radius:18px;background:radial-gradient(circle at 20% 0,rgba(80,186,196,.12),transparent 30%),linear-gradient(145deg,#0b151a,#17131c)}.es-close{position:absolute!important;right:12px;top:12px;width:36px!important;height:36px!important;padding:0!important}.es-help,.es-count{font-size:.73rem;opacity:.75}.es-clock{display:flex;gap:16px;align-items:center;padding:12px;border:1px solid rgba(88,194,207,.2);border-radius:13px}.es-ring{position:relative;width:112px;height:112px;border-radius:50%;border:1px solid rgba(100,205,216,.35);display:grid;place-items:center;flex:none}.es-ring i{position:absolute;width:42%;height:42%;left:29%;top:29%;border-radius:50% 50% 12% 50%;transform:rotate(calc(var(--i)*90deg)) translateY(-38px) rotate(-45deg);background:rgba(72,83,102,.35);border:1px solid rgba(112,206,216,.2)}.es-ring i.on{background:radial-gradient(circle,#77dbe7,#356e88);box-shadow:0 0 16px rgba(92,219,230,.35)}.es-ring strong{z-index:2}.es-clock>div:last-child{display:grid;gap:5px}.es-focus,.es-hero{display:grid;gap:4px;margin:10px 0;padding:10px;border:1px solid rgba(183,129,211,.2);border-radius:10px}.es-focus span,.es-hero span{font-size:.7rem;line-height:1.45}.es-grid,.es-gifts{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.es-grid article,.es-gifts label{display:grid;gap:5px;padding:10px;border:1px solid rgba(89,193,204,.18);border-radius:11px;background:rgba(255,255,255,.02)}.es-grid article>span,.es-gifts small{font-size:.6rem;color:#9eb8c2}.es-grid p,.es-gifts p{font-size:.7rem;line-height:1.4;margin:0}.es-gifts label{display:flex!important}.es-gifts label.active{border-color:rgba(99,208,219,.5);background:rgba(63,159,169,.08)}@media(max-width:700px){.esper-build-tools{align-items:flex-start;flex-direction:column}.es-grid,.es-gifts{grid-template-columns:1fr}.es-dialog{padding:20px 14px}.es-clock{align-items:flex-start}}`;document.head.appendChild(st);
 function boot(){const c=document.getElementById('classesEditor'),s=document.getElementById('skillsEditor');if(!c||!s){setTimeout(boot,100);return}const q=()=>requestAnimationFrame(renderAll);[c,s].forEach(el=>{el.addEventListener('input',q);el.addEventListener('change',q);new MutationObserver(q).observe(el,{childList:true})});document.addEventListener('aestra:character-loaded',()=>{charId=null;load()});document.getElementById('buildMenuBody')&&new MutationObserver(q).observe(document.getElementById('buildMenuBody'),{childList:true,subtree:false});const a=document.getElementById('sessionActionBody');if(a)new MutationObserver(()=>requestAnimationFrame(inject)).observe(a,{childList:true,subtree:false,attributes:true,attributeFilter:['data-mode']});load();setTimeout(q,500)}boot();
})();