// Natural Fantasy Invoker — scene wellsprings, invocation browser and heroic-aware reference tools.
(function(){
 const CONFIG=window.AESTRA_CONFIG||{},norm=v=>String(v||'').trim().toLowerCase(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rows=id=>[...(document.getElementById(id)?.querySelectorAll('.entry-row')||[])],vals=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
 const W=['Air','Earth','Fire','Lightning','Water'];
 const DATA={
  Air:[['Aero Blast',1,'blast','20 air damage.'],['Aero Hex',2,'hex','Until start of your next turn, target suffers +5 damage from bolt and fire sources.'],['Breeze',3,'other','Target recovers 30 HP.'],['Twister',3,'other','10 air damage and target suffers dazed.']],
  Earth:[['Geo Blast',1,'blast','20 earth damage.'],['Geo Hex',2,'hex','Until start of your next turn, target suffers +5 damage from air and ice sources.'],['Growth',3,'other','Target recovers 30 HP.'],['Quicksand',3,'other','10 earth damage and target suffers slow.']],
  Fire:[['Pyro Blast',1,'blast','20 fire damage.'],['Pyro Hex',2,'hex','Until start of your next turn, target suffers +5 damage from earth and ice sources.'],['Burst',3,'other','10 fire damage and target suffers shaken.'],['Smoke',3,'other','Target loses 20 MP and suffers weak.']],
  Lightning:[['Electro Blast',1,'blast','20 bolt damage.'],['Electro Hex',2,'hex','Until start of your next turn, target suffers +5 damage from earth and fire sources.'],['Static',3,'other','10 bolt damage and target suffers slow.'],['Thunder',3,'other','Target loses 20 MP and suffers dazed.']],
  Water:[['Hydro Blast',1,'blast','20 ice damage.'],['Hydro Hex',2,'hex','Until start of your next turn, target suffers +5 damage from air and bolt sources.'],['Chill',3,'other','Target loses 20 MP and suffers shaken.'],['Frostbite',3,'other','10 ice damage and target suffers weak.']]
 };
 let sb=null,charId=null,loading=false,state={scene:[],inner:null};
 const present=()=>rows('classesEditor').some(r=>norm(vals(r)[0])==='invoker');
 const skill=n=>rows('skillsEditor').map(r=>{const v=vals(r);return{name:v[0],rank:+v[1]||0,source:v[2]}}).find(x=>norm(x.name)===norm(n)&&norm(x.source).includes('invoker'))?.rank||0;
 const heroic=n=>rows('skillsEditor').some(r=>norm(vals(r)[0])===norm(n));
 const level=()=>+document.getElementById('level')?.value||1;
 async function client(){if(sb)return sb;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=m.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);return sb}
 async function resolve(){const c=await client(),{data:{user}}=await c.auth.getUser();if(!user)return null;const name=String(document.getElementById('charName')?.value||'').trim();if(!name)return null;const {data,error}=await c.from('characters').select('id,invoker_options,updated_at').eq('owner_id',user.id).eq('campaign_id',CONFIG.campaignId).eq('name',name).order('updated_at',{ascending:false}).limit(1);if(error)throw error;return data?.[0]||null}
 function clean(o={}){let scene=Array.isArray(o.scene)?o.scene.filter(x=>W.includes(x)).slice(0,2):[];return{scene:[...new Set(scene)],inner:W.includes(o.inner)?o.inner:null}}
 async function load(){if(loading)return;loading=true;try{const r=await resolve();if(r){charId=r.id;state=clean(r.invoker_options||{})}}catch(e){console.warn('Invoker sync unavailable',e)}finally{loading=false}renderAll()}
 async function save(){state=clean(state);if(!charId){const r=await resolve().catch(()=>null);charId=r?.id||null}if(!charId)return;const c=await client();await c.from('characters').update({invoker_options:state,updated_at:new Date().toISOString()}).eq('id',charId).eq('campaign_id',CONFIG.campaignId)}
 function modal(){let m=document.getElementById('invokerModal');if(m)return m;m=document.createElement('div');m.id='invokerModal';m.className='iv-modal hidden';m.innerHTML='<div class="iv-dialog"><button class="iv-close">×</button><div id="ivBody"></div></div>';document.body.appendChild(m);m.querySelector('.iv-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
 function available(){return [...new Set([...state.scene,...(heroic('Inner Wellspring')&&state.inner?[state.inner]:[])])];}
 function scaled(text,type){let t=text,lv=level(),exp=skill('Wellspring Expansion');if(type==='blast'&&exp)t=t.replace(/20 (air|earth|fire|bolt|ice) damage/i,`${20+(lv>=40?10:lv>=20?5:0)+exp} $1 damage`);else if(type==='blast'&&lv>=20)t=t.replace(/20 (air|earth|fire|bolt|ice) damage/i,`${20+(lv>=40?10:5)} $1 damage`);if((/recovers 30 HP/i.test(t))&&lv>=20)t=t.replace('30 HP',`${30+(lv>=40?20:10)} HP`);if((/loses 20 MP/i.test(t))&&lv>=20)t=t.replace('20 MP',`${20+(lv>=40?20:10)} MP`);if(type==='hex'&&exp)t=t.replace('+5 damage',`+${5+exp} damage`);return t}
 function open(){const m=modal(),b=document.getElementById('ivBody'),rank=skill('Invocation'),link=skill('Linked Invocation'),harm=skill('Elemental Harmony'),exp=skill('Wellspring Expansion'),avail=available();b.innerHTML=`<p class="eyebrow">Natural Fantasy · Invoker</p><h2>Wellspring Chamber</h2><div class="iv-section"><strong>Scene Wellsprings</strong><p>The GM determines two wellsprings present in each scene.</p><div class="iv-wells">${W.map(w=>`<button data-well="${w}" class="${state.scene.includes(w)?'active':''}">${w}</button>`).join('')}</div>${heroic('Inner Wellspring')?`<label>Inner Wellspring<select id="ivInner"><option value="">Choose after a rest…</option>${W.map(w=>`<option ${state.inner===w?'selected':''}>${w}</option>`).join('')}</select></label>`:''}</div><div class="iv-meta"><span>Invocation SL ${rank}</span><span>Base cost 5 MP</span>${link?`<span>Linked: +10 MP/target · max +${link*10} MP</span>`:''}${harm?`<span>Elemental Harmony: healing +${harm*5} with an elemental present</span>`:''}${exp?`<span>Wellspring Expansion SL ${exp}</span>`:''}</div><div class="iv-grid">${avail.length?avail.flatMap(w=>DATA[w].filter(x=>rank>=x[1]).map(x=>`<article class="iv-card ${x[2]}"><span>${w} · ${x[2]}</span><strong>${x[0]}</strong><p>${esc(scaled(x[3],x[2]))}</p><small>${x[2]==='hex'?'Hex lasts until start of your next turn.':'Invocation targets one visible creature before Linked Invocation.'}</small></article>`)).join(''):'<p class="muted">Choose this scene’s wellsprings to reveal available invocations.</p>'}</div>${heroic('Bend Magic')?'<div class="iv-hero"><b>Bend Magic</b><span>Even-result offensive spell against you → free non-hex invocation against that enemy, 0 MP, no Linked Invocation.</span></div>':''}${heroic('Strength of Five Wellsprings')?'<div class="iv-hero"><b>Strength of Five Wellsprings</b><span>After invoking: you and one ally raise an Attribute one die size. Air=INS · Earth=any · Fire=DEX · Lightning=MIG · Water=WLP.</span></div>':''}<div class="iv-actions"><button id="ivReset" class="ghost">New Scene · Clear Wellsprings</button></div>`;
 b.querySelectorAll('[data-well]').forEach(x=>x.onclick=()=>{const w=x.dataset.well;if(state.scene.includes(w))state.scene=state.scene.filter(v=>v!==w);else if(state.scene.length<2)state.scene.push(w);save();open();renderAll()});b.querySelector('#ivInner')?.addEventListener('change',e=>{state.inner=e.target.value||null;save();open();renderAll()});b.querySelector('#ivReset').onclick=()=>{state.scene=[];save();open();renderAll()};m.classList.remove('hidden')}
 function renderBuild(){const old=document.querySelector('.invoker-build-tools');if(!present()){old?.remove();return}const body=document.getElementById('buildMenuBody');if(!body)return;const section=document.querySelector('.build-tab.active')?.dataset.build;if(!['classes','skills'].includes(section)){old?.remove();return}let box=old;if(!box){box=document.createElement('section');box.className='invoker-build-tools';(document.getElementById('classHierarchy')||body.querySelector('.build-actions'))?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<div><p class="eyebrow">Natural Fantasy · Invoker</p><strong>Wellspring Chamber</strong><small>${available().length?available().join(' · '):'No scene wellsprings chosen'} · Invocation SL ${skill('Invocation')}</small></div><button class="secondary">Open Invocations</button>`;box.querySelector('button').onclick=open}
 function inject(){const host=document.getElementById('sessionActionBody');if(!host)return;const mode=host.dataset.mode,old=host.querySelector('[data-invoker-action]');if(!present()||!skill('Invocation')||!['skills','favourites'].includes(mode)){old?.remove();return}if(old)return;const c=document.createElement('article');c.className='a2-card';c.dataset.invokerAction='1';c.innerHTML=`<button class="a2-open"><span class="a2-kind">◈ SKILL · INVOKER</span><strong>Invocation</strong><small>${available().join(' · ')||'Choose scene wellsprings'}</small><p>Draw from an available wellspring. Base cost: 5 MP.</p><span class="a2-more">Open chamber ›</span></button>`;c.querySelector('button').onclick=e=>{e.stopPropagation();open()};host.prepend(c)}
 function renderAll(){renderBuild();inject()}
 const st=document.createElement('style');st.textContent=`.invoker-build-tools{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px;padding:12px;border:1px solid rgba(124,180,157,.3);border-radius:12px;background:linear-gradient(110deg,rgba(57,104,94,.13),rgba(168,126,63,.06))}.invoker-build-tools>div{display:grid;gap:3px}.invoker-build-tools .eyebrow{margin:0}.invoker-build-tools small{opacity:.7}.iv-modal{position:fixed;inset:0;z-index:2370;display:grid;place-items:center;padding:14px;background:rgba(3,7,7,.91)}.iv-modal.hidden{display:none!important}.iv-dialog{position:relative;width:min(980px,96vw);max-height:93vh;overflow:auto;padding:24px;border:1px solid rgba(109,174,151,.42);border-radius:18px;background:radial-gradient(circle at 50% 0,rgba(79,132,104,.12),transparent 34%),linear-gradient(145deg,#0d1615,#171515)}.iv-close{position:absolute!important;right:12px;top:12px;width:36px!important;height:36px!important;padding:0!important}.iv-section{display:grid;gap:8px;padding:12px;border:1px solid rgba(112,169,144,.2);border-radius:12px}.iv-wells,.iv-meta,.iv-actions{display:flex;gap:7px;flex-wrap:wrap}.iv-wells button.active{background:rgba(91,148,117,.23)!important;border-color:rgba(132,198,157,.7)!important}.iv-meta{margin:10px 0}.iv-meta span{font-size:.64rem;padding:5px 8px;border:1px solid rgba(200,166,95,.18);border-radius:999px;color:#c8b987}.iv-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.iv-card{display:grid;gap:5px;padding:11px;border:1px solid rgba(112,169,144,.2);border-radius:11px;background:rgba(255,255,255,.02)}.iv-card>span{font-size:.56rem;text-transform:uppercase;letter-spacing:.09em;color:#9cb79f}.iv-card p{font-size:.73rem;line-height:1.45;margin:0}.iv-card small{opacity:.63}.iv-card.hex{border-color:rgba(153,105,170,.28)}.iv-hero{display:grid;gap:3px;margin-top:9px;padding:10px;border:1px solid rgba(200,166,95,.22);border-radius:10px}.iv-hero span{font-size:.7rem;line-height:1.4}@media(max-width:700px){.invoker-build-tools{align-items:flex-start;flex-direction:column}.iv-grid{grid-template-columns:1fr}.iv-dialog{padding:20px 14px}}`;document.head.appendChild(st);
 function boot(){const c=document.getElementById('classesEditor'),s=document.getElementById('skillsEditor');if(!c||!s){setTimeout(boot,100);return}const q=()=>requestAnimationFrame(renderAll);[c,s].forEach(el=>{el.addEventListener('input',q);el.addEventListener('change',q);new MutationObserver(q).observe(el,{childList:true})});document.addEventListener('aestra:character-loaded',()=>{charId=null;load()});document.getElementById('buildMenuBody')&&new MutationObserver(q).observe(document.getElementById('buildMenuBody'),{childList:true,subtree:false});const a=document.getElementById('sessionActionBody');if(a)new MutationObserver(()=>requestAnimationFrame(inject)).observe(a,{childList:true,subtree:false,attributes:true,attributeFilter:['data-mode']});load();setTimeout(q,500)}boot();
})();