// Natural Fantasy Merchant — Trade Points, contacts/materials and prosperity tracker.
(function(){
 const CONFIG=window.AESTRA_CONFIG||{},norm=v=>String(v||'').trim().toLowerCase(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rows=id=>[...(document.getElementById(id)?.querySelectorAll('.entry-row')||[])],vals=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
 let sb=null,charId=null,loading=false,state={trade:0,prosperity:[],realTreasureUsed:false};
 const present=()=>rows('classesEditor').some(r=>norm(vals(r)[0])==='merchant');
 const skill=n=>rows('skillsEditor').map(r=>{const v=vals(r);return{name:v[0],rank:+v[1]||0,source:v[2]}}).find(x=>norm(x.name)===norm(n)&&norm(x.source).includes('merchant'))?.rank||0;
 const heroic=n=>rows('skillsEditor').some(r=>norm(vals(r)[0])===norm(n));
 const cap=()=>skill('Winds of Trade')?skill('Winds of Trade')+3:0;
 async function client(){if(sb)return sb;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=m.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);return sb}
 async function resolve(){const c=await client(),{data:{user}}=await c.auth.getUser();if(!user)return null;const name=String(document.getElementById('charName')?.value||'').trim();if(!name)return null;const {data,error}=await c.from('characters').select('id,merchant_options,updated_at').eq('owner_id',user.id).eq('campaign_id',CONFIG.campaignId).eq('name',name).order('updated_at',{ascending:false}).limit(1);if(error)throw error;return data?.[0]||null}
 function clean(o={}){const max=cap();return{trade:Math.max(0,Math.min(max,Number(o.trade)||0)),prosperity:Array.isArray(o.prosperity)?o.prosperity.filter(x=>x&&x.name).map(x=>({name:String(x.name),value:Math.max(0,+x.value||0)})):[],realTreasureUsed:!!o.realTreasureUsed}}
 async function load(){if(loading)return;loading=true;try{const r=await resolve();if(r){charId=r.id;state=clean(r.merchant_options||{})}}catch(e){console.warn('Merchant sync unavailable',e)}finally{loading=false}renderAll()}
 async function save(){state=clean(state);if(!charId){const r=await resolve().catch(()=>null);charId=r?.id||null}if(!charId)return;const c=await client();await c.from('characters').update({merchant_options:state,updated_at:new Date().toISOString()}).eq('id',charId).eq('campaign_id',CONFIG.campaignId)}
 function gain(n){state.trade=Math.min(cap(),state.trade+n);save();open();renderAll()}
 function spend(n){if(state.trade<n)return alert('Not enough Trade Points.');state.trade-=n;save();open();renderAll();return true}
 function modal(){let m=document.getElementById('merchantModal');if(m)return m;m=document.createElement('div');m.id='merchantModal';m.className='me-modal hidden';m.innerHTML='<div class="me-dialog"><button class="me-close">×</button><div id="meBody"></div></div>';document.body.appendChild(m);m.querySelector('.me-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
 function prosperityEffects(v){const out=[];if(v>=10)out.push('Zenit costs are halved within 1 travel day.');if(v>=15)out.push('Free rests; travel rolls in the area never use a die above d8.');if(v>=20)out.push('Villains in the area spend twice as many Ultima Points.');return out.join(' ')||'No prosperity threshold reached yet.'}
 function open(){const m=modal(),b=document.getElementById('meBody'),winds=skill('Winds of Trade'),heard=skill('I’ve Heard of It!'),stock=skill('Private Stock'),real=skill('Real Treasure'),exp=skill('Expiration Date'),better=heroic('For a Better Future');b.innerHTML=`<p class="eyebrow">Natural Fantasy · Merchant</p><h2>Trade Ledger</h2><div class="me-wallet"><span>Trade Points</span><strong>${state.trade} / ${cap()}</strong></div>${winds?`<div class="me-actions"><button id="meRest" class="primary">Rest where commerce is possible · +${winds+1} TP</button><button id="meSpend2">Spend 2 TP · Material / Rare Item / Contact</button>${real?`<button id="meTreasure" ${state.realTreasureUsed?'disabled':''}>Real Treasure · +${real+1} TP</button>`:''}<button id="meResetSession" class="ghost">New Session · Reset Real Treasure</button></div>`:'<p class="muted">Learn Winds of Trade to generate and spend Trade Points.</p>'}<div class="me-reference">${heard?`<article><b>I’ve Heard of It! SL ${heard}</b><span>Spend 1 TP to add +${heard*2} to a Check Result examining a creature, item, or location.</span><button data-spend="1">Spend 1 TP</button></article>`:''}${stock?`<article><b>Private Stock SL ${stock}</b><span>Spend 1 TP to ignore an IP cost of ${stock+2} or less for you or another PC.</span><button data-spend="1">Spend 1 TP</button></article>`:''}${exp?`<article><b>Expiration Date SL ${exp}</b><span>A non-damaging potion/delicacy that would restore HP may instead deal ${Math.floor((+document.getElementById('level')?.value||1)/2)+exp*10} poison damage; halve if affecting 2+ creatures.</span></article>`:''}</div>${better?`<section class="me-pros"><div class="me-pros-head"><div><p class="eyebrow">Heroic Skill</p><strong>For a Better Future</strong></div><button id="meAddSettlement">+ Settlement</button></div><p>For non-story-alteration Fabula Point costs, you may spend the same number of Trade Points instead. When gaining 2+ TP from Real Treasure or Winds of Trade, you may gain exactly 1 TP instead and donate prosperity equal to Winds SL + Real Treasure SL (${winds+real}).</p><div>${state.prosperity.map((x,i)=>`<article><input data-pros-name="${i}" value="${esc(x.name)}"><input data-pros-value="${i}" type="number" min="0" value="${x.value}"><button data-donate="${i}">Donate +${winds+real}</button><small>${esc(prosperityEffects(x.value))}</small><button data-pros-remove="${i}" class="ghost">Remove</button></article>`).join('')||'<p class="muted">No settlements tracked yet.</p>'}</div></section>`:''}`;
 b.querySelector('#meRest')?.addEventListener('click',()=>gain(winds+1));b.querySelector('#meSpend2')?.addEventListener('click',()=>spend(2));b.querySelector('#meTreasure')?.addEventListener('click',()=>{if(state.realTreasureUsed)return;state.realTreasureUsed=true;state.trade=Math.min(cap(),state.trade+real+1);save();open();renderAll()});b.querySelector('#meResetSession')?.addEventListener('click',()=>{state.realTreasureUsed=false;save();open();renderAll()});b.querySelectorAll('[data-spend]').forEach(x=>x.onclick=()=>spend(+x.dataset.spend));b.querySelector('#meAddSettlement')?.addEventListener('click',()=>{state.prosperity.push({name:'New Settlement',value:0});save();open()});b.querySelectorAll('[data-pros-name]').forEach(x=>x.onchange=()=>{state.prosperity[+x.dataset.prosName].name=x.value;save()});b.querySelectorAll('[data-pros-value]').forEach(x=>x.onchange=()=>{state.prosperity[+x.dataset.prosValue].value=Math.max(0,+x.value||0);save();open()});b.querySelectorAll('[data-donate]').forEach(x=>x.onclick=()=>{const i=+x.dataset.donate;if(state.trade<1)return alert('For a Better Future donation replaces a gain of 2+ TP with exactly 1 TP. Use this button when that trigger occurs; it does not spend existing TP.');state.prosperity[i].value+=winds+real;save();open()});b.querySelectorAll('[data-pros-remove]').forEach(x=>x.onclick=()=>{state.prosperity.splice(+x.dataset.prosRemove,1);save();open()});m.classList.remove('hidden')}
 function renderBuild(){const old=document.querySelector('.merchant-build-tools');if(!present()){old?.remove();return}const body=document.getElementById('buildMenuBody');if(!body)return;const sec=document.querySelector('.build-tab.active')?.dataset.build;if(!['classes','skills'].includes(sec)){old?.remove();return}let box=old;if(!box){box=document.createElement('section');box.className='merchant-build-tools';(document.getElementById('classHierarchy')||body.querySelector('.build-actions'))?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<div><p class="eyebrow">Natural Fantasy · Merchant</p><strong>Trade Ledger</strong><small>${state.trade}/${cap()} Trade Points${state.prosperity.length?` · ${state.prosperity.length} settlement${state.prosperity.length===1?'':'s'} tracked`:''}</small></div><button class="secondary">Open Ledger</button>`;box.querySelector('button').onclick=open}
 function inject(){const host=document.getElementById('sessionActionBody');if(!host)return;const mode=host.dataset.mode,old=host.querySelector('[data-merchant-action]');if(!present()||!['skills','favourites'].includes(mode)){old?.remove();return}if(old)return;const c=document.createElement('article');c.className='a2-card';c.dataset.merchantAction='1';c.innerHTML=`<button class="a2-open"><span class="a2-kind">¤ SKILL · MERCHANT</span><strong>Trade Ledger</strong><small>${state.trade}/${cap()} Trade Points</small><p>Spend Trade Points on contacts, materials, stock, and merchant abilities.</p><span class="a2-more">Open ledger ›</span></button>`;c.querySelector('button').onclick=e=>{e.stopPropagation();open()};host.prepend(c)}
 function renderAll(){state=clean(state);renderBuild();inject()}
 const st=document.createElement('style');st.textContent=`.merchant-build-tools{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px;padding:12px;border:1px solid rgba(190,150,77,.32);border-radius:12px;background:linear-gradient(110deg,rgba(111,82,31,.15),rgba(70,95,72,.06))}.merchant-build-tools>div{display:grid;gap:3px}.merchant-build-tools .eyebrow{margin:0}.merchant-build-tools small{opacity:.7}.me-modal{position:fixed;inset:0;z-index:2375;display:grid;place-items:center;padding:14px;background:rgba(7,5,2,.91)}.me-modal.hidden{display:none!important}.me-dialog{position:relative;width:min(940px,96vw);max-height:93vh;overflow:auto;padding:24px;border:1px solid rgba(196,153,77,.43);border-radius:18px;background:radial-gradient(circle at 15% 0,rgba(170,124,50,.12),transparent 32%),linear-gradient(145deg,#17130c,#151515)}.me-close{position:absolute!important;right:12px;top:12px;width:36px!important;height:36px!important;padding:0!important}.me-wallet{display:flex;justify-content:space-between;align-items:center;margin:12px 0;padding:14px;border:1px solid rgba(197,155,78,.25);border-radius:12px}.me-wallet strong{font:700 1.6rem Georgia,serif;color:#e2c170}.me-actions{display:flex;gap:7px;flex-wrap:wrap}.me-reference{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.me-reference article,.me-pros article{display:grid;gap:5px;padding:11px;border:1px solid rgba(197,155,78,.18);border-radius:10px;background:rgba(255,255,255,.02)}.me-reference span,.me-pros p,.me-pros small{font-size:.71rem;line-height:1.45}.me-pros{margin-top:13px;padding-top:12px;border-top:1px solid rgba(197,155,78,.18)}.me-pros-head{display:flex;justify-content:space-between;align-items:center}.me-pros-head .eyebrow{margin:0}.me-pros article{grid-template-columns:minmax(120px,1fr) 90px auto;align-items:center}.me-pros article small{grid-column:1/-1;opacity:.72}@media(max-width:700px){.merchant-build-tools{align-items:flex-start;flex-direction:column}.me-reference{grid-template-columns:1fr}.me-actions{width:100%}.me-actions button{flex:1 1 140px}.me-pros article{grid-template-columns:1fr}.me-pros article small{grid-column:auto}.me-dialog{padding:20px 14px}}`;document.head.appendChild(st);
 function boot(){const c=document.getElementById('classesEditor'),s=document.getElementById('skillsEditor');if(!c||!s){setTimeout(boot,100);return}const q=()=>requestAnimationFrame(renderAll);[c,s].forEach(el=>{el.addEventListener('input',q);el.addEventListener('change',q);new MutationObserver(q).observe(el,{childList:true})});document.addEventListener('aestra:character-loaded',()=>{charId=null;load()});document.getElementById('buildMenuBody')&&new MutationObserver(q).observe(document.getElementById('buildMenuBody'),{childList:true,subtree:false});const a=document.getElementById('sessionActionBody');if(a)new MutationObserver(()=>requestAnimationFrame(inject)).observe(a,{childList:true,subtree:false,attributes:true,attributeFilter:['data-mode']});load();setTimeout(q,500)}boot();
})();