// Techno Fantasy Mutant — learned theriomorphs, transformation loadout and Genoclepsis reference.
(function(){
 const CONFIG=window.AESTRA_CONFIG||{},norm=v=>String(v||'').trim().toLowerCase(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rows=id=>[...(document.getElementById(id)?.querySelectorAll('.entry-row')||[])],vals=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
 const FORMS={
 Amphibia:'Breathe underwater and see in dim light; HP recovery gains +5 HP and may also clear one status effect.',
 Arpaktida:'Insight counts one die size higher (max d12); first time each turn you damage a creature in Crisis, deal +5 damage to those Crisis targets.',
 Dynamotheria:'Might counts one die size higher (max d12); successful Might Clock Checks may fill/erase 1 additional section.',
 Electrophora:'Attack/spell damage may become bolt; unarmed strikes that deal 20+ HP also inflict slow.',
 Neurophagoida:'Biophagy also recovers MP equal to 4 + Theriomorphosis SL.',
 Placophora:'Defense may equal 13 + half Theriomorphosis SL, if better.',
 Pneumophora:'Attack/spell damage may become air; unarmed strikes that deal 20+ HP also inflict weak.',
 Polypoda:'Unarmed strike attacks gain multi (3).',
 Pterotheria:'You can fly; melee attacks can target flying creatures and most melee attacks cannot target you while freely airborne. Air/bolt/ice damage suppresses this until next turn.',
 Pyrophora:'Attack/spell damage may become fire; unarmed strikes that deal 20+ HP also inflict dazed.',
 Tachytheria:'Dexterity counts one die size higher (max d12); successful Dexterity Clock Checks may fill/erase 1 additional section.',
 Toxicophora:'Attack/spell damage may become poison; unarmed strikes that deal 20+ HP also inflict poisoned.'
 };
 let sb=null,charId=null,state={learned:[],active:[]};
 const present=()=>rows('classesEditor').some(r=>norm(vals(r)[0])==='mutant');
 const rank=n=>rows('skillsEditor').map(r=>{const v=vals(r);return{name:v[0],rank:+v[1]||0,source:v[2]}}).find(x=>norm(x.name)===norm(n)&&norm(x.source).includes('mutant'))?.rank||0;
 const heroic=n=>rows('skillsEditor').some(r=>norm(vals(r)[0])===norm(n));
 async function client(){if(sb)return sb;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=m.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);return sb}
 async function resolve(){const c=await client(),{data:{user}}=await c.auth.getUser();if(!user)return null;const name=document.getElementById('charName')?.value?.trim();if(!name)return null;const {data}=await c.from('characters').select('id,mutant_options,updated_at').eq('owner_id',user.id).eq('campaign_id',CONFIG.campaignId).eq('name',name).order('updated_at',{ascending:false}).limit(1);return data?.[0]||null}
 function clean(o={}){const max=rank('Theriomorphosis'),activeMax=heroic('Greater Theriomorphosis')?3:2;const learned=Array.isArray(o.learned)?o.learned.filter(x=>FORMS[x]).slice(0,max):[];return{learned,active:Array.isArray(o.active)?o.active.filter(x=>learned.includes(x)).slice(0,activeMax):[]}}
 async function load(){const r=await resolve().catch(()=>null);if(r){charId=r.id;state=clean(r.mutant_options||{})}renderAll()}
 async function save(){state=clean(state);if(!charId)charId=(await resolve().catch(()=>null))?.id||null;if(!charId)return;const c=await client();await c.from('characters').update({mutant_options:state,updated_at:new Date().toISOString()}).eq('id',charId).eq('campaign_id',CONFIG.campaignId)}
 function modal(){let m=document.getElementById('mutantModal');if(m)return m;m=document.createElement('div');m.id='mutantModal';m.className='mu-modal hidden';m.innerHTML='<div class="mu-dialog"><button class="mu-close">×</button><div id="muBody"></div></div>';document.body.appendChild(m);m.querySelector('.mu-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
 function hpCost(){const hp=+document.getElementById('hpNow')?.textContent||0;return Math.floor(hp/3)}
 function configure(){const m=modal(),b=document.getElementById('muBody'),max=rank('Theriomorphosis');b.innerHTML=`<p class="eyebrow">Techno Fantasy · Mutant</p><h2>Learned Theriomorphs</h2><p class="mu-help">Theriomorphosis SL ${max}: learn one theriomorph per Skill Level.</p><div class="mu-list">${Object.entries(FORMS).map(([n,e])=>`<label class="${state.learned.includes(n)?'active':''}"><input type="checkbox" value="${n}" ${state.learned.includes(n)?'checked':''} ${!state.learned.includes(n)&&state.learned.length>=max?'disabled':''}><span><strong>${n}</strong><small>${esc(e)}</small></span></label>`).join('')}</div><p>${state.learned.length}/${max} learned</p>`;b.querySelectorAll('input').forEach(x=>x.onchange=()=>{if(x.checked&&state.learned.length<max)state.learned.push(x.value);else if(!x.checked){state.learned=state.learned.filter(v=>v!==x.value);state.active=state.active.filter(v=>v!==x.value)}save();configure();renderAll()});m.classList.remove('hidden')}
 function open(){const m=modal(),b=document.getElementById('muBody'),activeMax=heroic('Greater Theriomorphosis')?3:2,cost=hpCost(),ak=rank('Akromorphosis');b.innerHTML=`<p class="eyebrow">Techno Fantasy · Mutant</p><h2>Mutation Chamber</h2><div class="mu-meta"><span>Theriomorphosis SL ${rank('Theriomorphosis')}</span><span>Current activation cost: ${cost} HP</span><span>Active limit: ${activeMax}</span></div><div class="mu-active"><b>Manifested forms</b><div>${state.learned.map(n=>`<button data-form="${n}" class="${state.active.includes(n)?'active':''}" ${!state.active.includes(n)&&state.active.length>=activeMax?'disabled':''}>${n}</button>`).join('')||'<span class="muted">No learned forms.</span>'}</div><small>Use Theriomorphosis as an action and spend one third of current HP, rounded down, to manifest the selected forms. The tracker does not deduct HP automatically.</small></div><div class="mu-effects">${state.active.map(n=>`<article><strong>${n}</strong><p>${esc(FORMS[n])}</p></article>`).join('')||'<p class="muted">No theriomorphs are currently manifested.</p>'}</div>${ak?`<div class="mu-ref"><b>Akromorphosis SL ${ak}</b><span>Unarmed strikes: +${6+ak*2} damage and +${ak} Accuracy. At turn start you may temporarily choose another weapon Category.</span>${heroic('Greater Akromorphosis')?'<small>Greater Akromorphosis adds Category-specific bonuses while that Category is active.</small>':''}</div>`:''}${rank('Genoclepsis')?`<div class="mu-ref"><b>Genoclepsis SL ${rank('Genoclepsis')}</b><span>After damaging an NPC, learn its Species and the GM chooses ${rank('Genoclepsis')} fitting theriomorph${rank('Genoclepsis')===1?'':'s'}; you may immediately pay the Theriomorphosis HP cost to manifest them.</span>${heroic('Mimeoclepsis')?'<small>Mimeoclepsis can also expose/learn eligible spells through Spell Mimic.</small>':''}</div>`:''}${rank('Ecdysis')?`<div class="mu-ref"><b>Ecdysis</b><span>After non-physical damage, spend 10 HP to gain Resistance to that type until Ecdysis is used again.</span>${heroic('Greater Ecdysis')?'<small>Greater Ecdysis may also clear all status effects and/or Scene-duration spells.</small>':''}</div>`:''}<div class="mu-actions"><button id="muEnd" class="ghost">End Transformation</button><button id="muConfigure" class="secondary">Configure Learned Forms</button></div>`;b.querySelectorAll('[data-form]').forEach(x=>x.onclick=()=>{const n=x.dataset.form;if(state.active.includes(n))state.active=state.active.filter(v=>v!==n);else if(state.active.length<activeMax)state.active.push(n);save();open();renderAll()});b.querySelector('#muEnd').onclick=()=>{state.active=[];save();open();renderAll()};b.querySelector('#muConfigure').onclick=configure;m.classList.remove('hidden')}
 function renderBuild(){const old=document.querySelector('.mutant-build-tools');if(!present()){old?.remove();return}const body=document.getElementById('buildMenuBody');if(!body)return;const sec=document.querySelector('.build-tab.active')?.dataset.build;if(!['classes','skills'].includes(sec)){old?.remove();return}let box=old;if(!box){box=document.createElement('section');box.className='mutant-build-tools';(document.getElementById('classHierarchy')||body.querySelector('.build-actions'))?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<div><p class="eyebrow">Techno Fantasy · Mutant</p><strong>Mutation Chamber</strong><small>${state.learned.length}/${rank('Theriomorphosis')} learned · ${state.active.length} active · ${hpCost()} HP current cost</small></div><button class="secondary">Open Mutations</button>`;box.querySelector('button').onclick=open}
 function inject(){const host=document.getElementById('sessionActionBody');if(!host)return;const old=host.querySelector('[data-mutant-action]'),mode=host.dataset.mode;if(!present()||!['skills','favourites'].includes(mode)){old?.remove();return}if(old)return;const c=document.createElement('article');c.className='a2-card';c.dataset.mutantAction='1';c.innerHTML=`<button class="a2-open"><span class="a2-kind">◈ SKILL · MUTANT</span><strong>Mutation Chamber</strong><small>${state.active.length} active · ${hpCost()} HP</small><p>Manage Theriomorphosis, Akromorphosis, Genoclepsis and Ecdysis.</p><span class="a2-more">Open mutations ›</span></button>`;c.querySelector('button').onclick=e=>{e.stopPropagation();open()};host.prepend(c)}
 function renderAll(){state=clean(state);renderBuild();inject()}
 const st=document.createElement('style');st.textContent=`.mutant-build-tools{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:10px;padding:12px;border:1px solid rgba(194,91,132,.3);border-radius:12px;background:linear-gradient(110deg,rgba(116,44,75,.13),rgba(78,116,66,.07))}.mutant-build-tools>div{display:grid;gap:3px}.mutant-build-tools .eyebrow{margin:0}.mutant-build-tools small{opacity:.7}.mu-modal{position:fixed;inset:0;z-index:2390;display:grid;place-items:center;padding:14px;background:rgba(8,5,9,.91)}.mu-modal.hidden{display:none!important}.mu-dialog{position:relative;width:min(980px,96vw);max-height:93vh;overflow:auto;padding:24px;border:1px solid rgba(192,91,133,.4);border-radius:18px;background:radial-gradient(circle at 20% 0,rgba(125,56,95,.12),transparent 30%),linear-gradient(145deg,#171013,#111815)}.mu-close{position:absolute!important;right:12px;top:12px;width:36px!important;height:36px!important;padding:0!important}.mu-meta,.mu-actions,.mu-active>div{display:flex;gap:7px;flex-wrap:wrap}.mu-meta span{font-size:.64rem;padding:5px 8px;border:1px solid rgba(199,118,153,.2);border-radius:999px}.mu-active,.mu-ref{display:grid;gap:7px;margin:10px 0;padding:10px;border:1px solid rgba(194,91,132,.18);border-radius:11px}.mu-active button.active{background:rgba(135,63,96,.25)!important;border-color:rgba(214,110,155,.65)!important}.mu-active small,.mu-ref span,.mu-ref small{font-size:.7rem;line-height:1.45}.mu-effects{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mu-effects article{padding:10px;border:1px solid rgba(194,91,132,.18);border-radius:10px;background:rgba(255,255,255,.02)}.mu-effects p{font-size:.7rem;line-height:1.45}.mu-list{display:grid;grid-template-columns:1fr 1fr;gap:7px}.mu-list label{display:flex!important;gap:8px;padding:9px;border:1px solid rgba(194,91,132,.16);border-radius:9px}.mu-list label.active{border-color:rgba(214,110,155,.55)}.mu-list span{display:grid;gap:3px}.mu-list small{font-size:.68rem;line-height:1.4;opacity:.75}@media(max-width:700px){.mutant-build-tools{align-items:flex-start;flex-direction:column}.mu-effects,.mu-list{grid-template-columns:1fr}.mu-dialog{padding:20px 14px}}`;document.head.appendChild(st);
 function boot(){const c=document.getElementById('classesEditor'),s=document.getElementById('skillsEditor');if(!c||!s){setTimeout(boot,100);return}const q=()=>requestAnimationFrame(renderAll);[c,s].forEach(el=>{el.addEventListener('input',q);el.addEventListener('change',q);new MutationObserver(q).observe(el,{childList:true})});document.addEventListener('aestra:character-loaded',()=>{charId=null;load()});document.getElementById('buildMenuBody')&&new MutationObserver(q).observe(document.getElementById('buildMenuBody'),{childList:true,subtree:false});const a=document.getElementById('sessionActionBody');if(a)new MutationObserver(()=>requestAnimationFrame(inject)).observe(a,{childList:true,subtree:false,attributes:true,attributeFilter:['data-mode']});load();setTimeout(q,500)}boot();
})();