// Rules-aware Core Rulebook calculations + contextual floating conflict alert.
const number=v=>Number(v)||0, norm=v=>String(v||'').trim().toLowerCase();
const CLASS_BENEFITS={arcanist:{mp:5},chimerist:{mp:5},darkblade:{hp:5,martial:['melee','armor']},elementalist:{mp:5},entropist:{mp:5},fury:{hp:5,martial:['melee','armor']},guardian:{hp:5,martial:['armor','shield']},loremaster:{mp:5},orator:{mp:5},rogue:{ip:2},sharpshooter:{hp:5,martial:['ranged','shield']},spiritist:{mp:5},tinkerer:{ip:2},wayfarer:{ip:2},weaponmaster:{hp:5,martial:['melee','shield']},chanter:{mp:5},commander:{hp:5,martial:['melee','ranged']},symbolist:{ip:2}};
const rowValues=id=>[...document.querySelectorAll(`#${id} .entry-row`)].map(r=>[...r.querySelectorAll('input,textarea')].map(x=>x.value));
const classes=()=>rowValues('classesEditor').map(v=>({name:v[0]||'',level:number(v[1])}));
const skills=()=>rowValues('skillsEditor').map(v=>({name:v[0]||'',rank:Math.max(0,number(v[1])),source:v[2]||''}));
const equipment=()=>rowValues('equipmentEditor').map(v=>({slot:v[0]||'',name:v[1]||'',def:number(v[2]),mdef:number(v[3]),init:number(v[4]),notes:v[5]||''}));
const skillRank=name=>skills().filter(s=>norm(s.name)===norm(name)).reduce((a,s)=>a+s.rank,0), heroic=name=>skillRank(name)>0;
function automaticBonuses(){let hp=0,mp=0,ip=0;for(const c of classes()){if(c.level<=0)continue;const b=CLASS_BENEFITS[norm(c.name)];if(b){hp+=b.hp||0;mp+=b.mp||0;ip+=b.ip||0}}hp+=skillRank('Fortress')*3;mp+=skillRank('Focused')*3;const level=number(document.getElementById('level')?.value);if(heroic('Extra HP'))hp+=level>=40?20:10;if(heroic('Extra MP'))mp+=level>=40?20:10;if(heroic('Extra IP'))ip+=4;return{hp,mp,ip}}
let lastAuto=null,applying=false;function applyAutomaticResourceDeltas(){const next=automaticBonuses();if(lastAuto===null){lastAuto=next;return next}if(applying)return next;const ids={hp:'hpOther',mp:'mpOther',ip:'ipOther'},changed=[];for(const k of ['hp','mp','ip']){const delta=next[k]-lastAuto[k],el=document.getElementById(ids[k]);if(delta&&el){el.value=number(el.value)+delta;changed.push(el)}}lastAuto=next;if(changed.length){applying=true;changed.forEach(el=>el.dispatchEvent(new Event('change',{bubbles:true})));applying=false}return next}
function equipmentFlags(){const eq=equipment();return{hasShield:eq.some(e=>norm(e.slot).includes('shield')||norm(e.notes).includes('shield')),hasMartialArmor:eq.some(e=>(norm(e.slot).includes('armor')||norm(e.notes).includes('armor'))&&norm(e.notes).includes('martial'))}}
function martialPermissions(){const p=new Set();for(const c of classes())for(const x of CLASS_BENEFITS[norm(c.name)]?.martial||[])p.add(x);return p}
function equipmentWarnings(){const p=martialPermissions(),w=[];for(const e of equipment()){const notes=norm(e.notes),slot=norm(e.slot);if(!notes.includes('martial'))continue;const needed=slot.includes('armor')||notes.includes('armor')?'armor':slot.includes('shield')||notes.includes('shield')?'shield':notes.includes('ranged')?'ranged':'melee';if(!p.has(needed))w.push(`${e.name||'Martial item'} requires martial ${needed} access.`)}return w}
function classWarnings(){const cs=classes().filter(c=>c.level>0),w=[],total=cs.reduce((a,c)=>a+c.level,0),level=number(document.getElementById('level')?.value);if(total!==level)w.push(`Class levels total ${total}; character level is ${level}.`);if(cs.some(c=>c.level>10))w.push('A Class cannot exceed level 10.');if(cs.filter(c=>c.level<10).length>3)w.push('You cannot have more than three non-mastered Classes.');return w}
function heroicWarnings(){const cs=classes(),mastered=n=>cs.some(c=>norm(c.name)===norm(n)&&c.level>=10),names=new Set(skills().filter(s=>norm(s.source).includes('heroic')).map(s=>norm(s.name))),w=[];const req={'adversity':['Darkblade'],'arcane echoes':['Arcanist'],'chimeric mastery':['Chimerist'],'comet':['Entropist'],'deep pockets':['Tinkerer'],'disarming rhetoric':['Orator'],'heartbreaker':['Darkblade'],'heroic companion':['Wayfarer'],'hope':['Spiritist'],'mathemagic':['Loremaster'],'monkey grip':['Fury'],'perfect aim':['Sharpshooter'],'pillage':['Rogue'],'powerful shot':['Sharpshooter'],'predictable!':['Loremaster'],'rampart':['Guardian'],'repetition':['Orator'],'revelation':['Arcanist'],'status immunity':['Wayfarer'],'tempest strike':['Weaponmaster'],'unbreakable':['Guardian'],'upgrade':['Tinkerer'],'vanish':['Rogue'],'volcano':['Elementalist']};for(const[h,rs]of Object.entries(req))if(names.has(h)&&!rs.some(mastered))w.push(`${h.replace(/\b\w/g,x=>x.toUpperCase())} requires the relevant mastered Class.`);if(names.has('powerful spell')&&!['Chimerist','Elementalist','Entropist','Spiritist'].some(mastered))w.push('Powerful Spell requires a relevant mastered Class.');if(names.has('powerful strike')&&!['Fury','Weaponmaster'].some(mastered))w.push('Powerful Strike requires Fury or Weaponmaster mastered.');if(names.has('perfect aim')&&skillRank('Warning Shot')<1)w.push('Perfect Aim also requires Warning Shot.');if(names.has('pillage')&&skillRank('Soul Steal')<1)w.push('Pillage also requires Soul Steal.');if(names.has('heroic companion')&&skillRank('Faithful Companion')<1)w.push('Heroic Companion also requires Faithful Companion.');return w}
let dismissedSignature='';function ensureAlert(){let a=document.getElementById('rulesAwareAlert');if(a)return a;a=document.createElement('aside');a.id='rulesAwareAlert';a.className='rules-alert hidden';a.innerHTML='<button class="rules-alert-head" type="button"><span class="rules-alert-symbol">!</span><span><b id="rulesAlertCount">Rules conflict</b><small>Tap to review</small></span><span class="rules-alert-chevron">⌄</span></button><div id="rulesAlertBody" class="rules-alert-body"></div><button id="rulesAlertDismiss" class="rules-alert-dismiss" type="button">Dismiss for now</button>';document.body.appendChild(a);a.querySelector('.rules-alert-head').onclick=()=>a.classList.toggle('expanded');a.querySelector('#rulesAlertDismiss').onclick=()=>{dismissedSignature=a.dataset.signature||'';a.classList.add('hidden');a.classList.remove('expanded')};return a}
function updateAlert(warnings){const a=ensureAlert(),sig=warnings.join('|');a.dataset.signature=sig;if(!warnings.length){a.classList.add('hidden');a.classList.remove('expanded');dismissedSignature='';return}if(sig!==dismissedSignature)a.classList.remove('hidden');document.getElementById('rulesAlertCount').textContent=`${warnings.length} rules conflict${warnings.length===1?'':'s'}`;document.getElementById('rulesAlertBody').innerHTML=warnings.map(x=>`<p><span>!</span>${x}</p>`).join('')}
function recalc(){applyAutomaticResourceDeltas();const flags=equipmentFlags();let defBonus=0;if(skillRank('Dodge')>0&&!flags.hasShield&&!flags.hasMartialArmor)defBonus=skillRank('Dodge');const def=document.getElementById('defenceText');if(def&&defBonus){const base=number(document.getElementById('dex')?.value?.replace?.('d',''))+number(document.getElementById('defenceOther')?.value)+equipment().reduce((a,e)=>a+e.def,0);def.textContent=base+defBonus}updateAlert([...classWarnings(),...heroicWarnings(),...equipmentWarnings()])}
function install(){ensureAlert();document.getElementById('rulesAwarePanel')?.remove();const sheet=document.getElementById('sheetView');if(!sheet)return;let queued=false;const queue=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;recalc()})};sheet.addEventListener('input',queue);sheet.addEventListener('change',queue);const ob=new MutationObserver(queue);['classesEditor','skillsEditor','equipmentEditor'].forEach(id=>{const x=document.getElementById(id);if(x)ob.observe(x,{childList:true})});const s=document.createElement('style');s.textContent=`.rules-alert{position:fixed;z-index:10000;top:14px;left:50%;transform:translateX(-50%);width:min(430px,calc(100vw - 24px));border:1px solid rgba(224,172,70,.72);border-radius:13px;background:rgba(17,15,18,.97);box-shadow:0 8px 30px rgba(0,0,0,.55),0 0 20px rgba(211,145,39,.12);overflow:hidden;color:#eee0bd}.rules-alert.hidden{display:none}.rules-alert-head{width:100%;display:flex;align-items:center;gap:10px;padding:9px 12px!important;border:0!important;background:transparent!important;text-align:left!important;color:inherit!important}.rules-alert-symbol{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#5b3918;border:1px solid #c78f37;color:#ffd889;font-weight:900}.rules-alert-head span:nth-child(2){display:grid;flex:1}.rules-alert-head b{font-family:Georgia,serif;font-size:.9rem;color:#f1cf86}.rules-alert-head small{font-size:.66rem;color:#9d927e}.rules-alert-chevron{transition:transform .15s}.rules-alert.expanded .rules-alert-chevron{transform:rotate(180deg)}.rules-alert-body,.rules-alert-dismiss{display:none}.rules-alert.expanded .rules-alert-body{display:block;padding:3px 13px 8px;border-top:1px solid rgba(202,159,75,.18)}.rules-alert-body p{display:flex;gap:8px;margin:8px 0;font-size:.82rem;line-height:1.35}.rules-alert-body p span{color:#e6a94d;font-weight:900}.rules-alert.expanded .rules-alert-dismiss{display:block;width:calc(100% - 24px);margin:0 12px 11px;padding:7px!important;font-size:.72rem!important;background:rgba(82,61,31,.35)!important;border-color:rgba(190,145,66,.34)!important}@media(max-width:600px){.rules-alert{top:7px}}`;document.head.appendChild(s);recalc()}
install();