// Actionable rules guidance for the floating ! orb.
(function(){
 const $=id=>document.getElementById(id), norm=v=>String(v||'').trim().toLowerCase(), num=v=>Number(v)||0;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rows=id=>[...($(id)?.querySelectorAll('.entry-row')||[])];
 const values=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
 const fire=el=>{if(!el)return;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))};
 const CLASS_BENEFITS={darkblade:['melee','armor'],fury:['melee','armor'],guardian:['armor','shield'],sharpshooter:['ranged','shield'],weaponmaster:['melee','shield']};
 function classes(){return rows('classesEditor').map((r,i)=>{const v=values(r);return{row:r,i,name:v[0]||'',level:num(v[1])}}).filter(x=>x.name&&x.level>0)}
 function skills(){return rows('skillsEditor').map((r,i)=>{const v=values(r);return{row:r,i,name:v[0]||'',rank:Math.max(0,num(v[1])),source:v[2]||''}})}
 function equipment(){return rows('equipmentEditor').map((r,i)=>{const v=values(r),notes=v[5]||'',slot=v[0]||'';return{row:r,i,slot,name:v[1]||'Equipment',notes,stored:/§AESTRAEQ:/.test(notes)||norm(slot).startsWith('loadout')}}).filter(x=>!x.stored)}
 const skillRank=name=>skills().filter(s=>norm(s.name)===norm(name)).reduce((n,s)=>n+s.rank,0);
 function mastered(name){return classes().some(c=>norm(c.name)===norm(name)&&c.level>=10)}
 function permissions(){const out=new Set();classes().forEach(c=>(CLASS_BENEFITS[norm(c.name)]||[]).forEach(x=>out.add(x)));return out}
 function goBuild(tab='classes'){
   document.querySelector('[data-mobile-page="build"]')?.click();
   document.querySelector(`[data-build="${tab}"]`)?.click();
   setTimeout(()=>document.getElementById('buildMenu')?.scrollIntoView({behavior:'smooth',block:'start'}),80);
   document.getElementById('rulesAwareAlert')?.classList.remove('expanded');
 }
 function collect(){const out=[],cs=classes(),level=num($('level')?.value),total=cs.reduce((s,c)=>s+c.level,0);
   if(total!==level)out.push({id:'class-total',title:'Class levels do not match',detail:`Your Classes add up to Level ${total}, but your Character Level is ${level}.`,button:`Set Character Level to ${total}`,kind:'fix',run:()=>{const el=$('level');if(!el)return;el.value=String(Math.max(1,Math.min(50,total)));fire(el)}});
   const over=cs.filter(c=>c.level>10);if(over.length)out.push({id:'class-max',title:'A Class is above Level 10',detail:`${over.map(c=>`${c.name} (${c.level})`).join(', ')}. A Class cannot exceed Level 10.`,button:'Fix to Level 10',kind:'fix',run:()=>over.forEach(c=>{const el=c.row.querySelectorAll('input,textarea,select')[1];el.value='10';fire(el)})});
   const nonMastered=cs.filter(c=>c.level<10);if(nonMastered.length>3)out.push({id:'too-many-classes',title:'Too many non-mastered Classes',detail:`You currently have ${nonMastered.length} Classes below Level 10. The tracker expects no more than three non-mastered Classes.`,button:'Review Classes',kind:'go',run:()=>goBuild('classes')});
   const heroicNames=new Set(skills().filter(s=>norm(s.source).includes('heroic')).map(s=>norm(s.name)));
   const req={'adversity':['Darkblade'],'arcane echoes':['Arcanist'],'chimeric mastery':['Chimerist'],'comet':['Entropist'],'deep pockets':['Tinkerer'],'disarming rhetoric':['Orator'],'heartbreaker':['Darkblade'],'heroic companion':['Wayfarer'],'hope':['Spiritist'],'mathemagic':['Loremaster'],'monkey grip':['Fury'],'perfect aim':['Sharpshooter'],'pillage':['Rogue'],'powerful shot':['Sharpshooter'],'predictable!':['Loremaster'],'rampart':['Guardian'],'repetition':['Orator'],'revelation':['Arcanist'],'status immunity':['Wayfarer'],'tempest strike':['Weaponmaster'],'unbreakable':['Guardian'],'upgrade':['Tinkerer'],'vanish':['Rogue'],'volcano':['Elementalist']};
   for(const [h,needed] of Object.entries(req))if(heroicNames.has(h)&&!needed.some(mastered))out.push({id:`heroic:${h}`,title:`${h.replace(/\b\w/g,x=>x.toUpperCase())} prerequisite`,detail:`This Heroic Skill requires ${needed.join(' or ')} to be mastered first.`,button:'Review Build',kind:'go',run:()=>goBuild('skills')});
   if(heroicNames.has('powerful spell')&&!['Chimerist','Elementalist','Entropist','Spiritist'].some(mastered))out.push({id:'heroic:powerful-spell',title:'Powerful Spell prerequisite',detail:'Powerful Spell requires a relevant spellcasting Class to be mastered.',button:'Review Build',kind:'go',run:()=>goBuild('skills')});
   if(heroicNames.has('powerful strike')&&!['Fury','Weaponmaster'].some(mastered))out.push({id:'heroic:powerful-strike',title:'Powerful Strike prerequisite',detail:'Powerful Strike requires Fury or Weaponmaster to be mastered.',button:'Review Build',kind:'go',run:()=>goBuild('skills')});
   if(heroicNames.has('perfect aim')&&skillRank('Warning Shot')<1)out.push({id:'skill:warning-shot',title:'Perfect Aim is missing Warning Shot',detail:'Perfect Aim also requires Warning Shot.',button:'Review Skills',kind:'go',run:()=>goBuild('skills')});
   if(heroicNames.has('pillage')&&skillRank('Soul Steal')<1)out.push({id:'skill:soul-steal',title:'Pillage is missing Soul Steal',detail:'Pillage also requires Soul Steal.',button:'Review Skills',kind:'go',run:()=>goBuild('skills')});
   if(heroicNames.has('heroic companion')&&skillRank('Faithful Companion')<1)out.push({id:'skill:faithful-companion',title:'Heroic Companion prerequisite',detail:'Heroic Companion also requires Faithful Companion.',button:'Review Skills',kind:'go',run:()=>goBuild('skills')});
   const p=permissions();for(const e of equipment()){const notes=norm(e.notes),slot=norm(e.slot);if(!notes.includes('martial'))continue;const need=slot.includes('armor')||notes.includes('armor')?'armor':slot.includes('shield')||notes.includes('shield')?'shield':notes.includes('ranged')?'ranged':'melee';if(!p.has(need))out.push({id:`equip:${e.i}`,title:`${e.name} needs martial training`,detail:`This equipped item requires martial ${need} access, which your current Classes do not provide. Stowed Loadout items are ignored.`,button:'Review Equipment',kind:'go',run:()=>goBuild('equipment')})}
   return out;
 }
 let busy=false;
 function render(){if(busy)return;const alert=$('rulesAwareAlert'),body=$('rulesAlertBody'),count=$('rulesAlertCount');if(!alert||!body||!count)return;const warnings=collect(),sig=warnings.map(x=>x.id).join('|');alert.dataset.smartRules='1';alert.dataset.signature=sig;if(!warnings.length){alert.classList.add('hidden');alert.classList.remove('expanded');count.textContent='Rules clear';body.innerHTML='';return}alert.classList.remove('hidden');count.textContent=`${warnings.length} rules conflict${warnings.length===1?'':'s'}`;busy=true;body.innerHTML=`<div class="smart-rules-intro"><strong>Rules Check</strong><small>These are based on the character data currently entered.</small></div>${warnings.map((w,i)=>`<article class="smart-rule-card" data-rule="${i}"><div class="smart-rule-icon">!</div><div class="smart-rule-copy"><strong>${esc(w.title)}</strong><p>${esc(w.detail)}</p><button type="button" class="smart-rule-action ${w.kind==='fix'?'is-fix':''}" data-rule-action="${i}">${esc(w.button)}</button></div></article>`).join('')}`;busy=false;body.querySelectorAll('[data-rule-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const w=warnings[num(b.dataset.ruleAction)];if(!w)return;w.run();setTimeout(render,30)});
 }
 function install(){const body=$('rulesAlertBody');if(!body)return;const s=document.createElement('style');s.id='smartRulesStyles';s.textContent=`#rulesAwareAlert.rules-orb .rules-alert-body:before{display:none!important}.smart-rules-intro{display:grid;gap:2px;margin:1px 2px 9px;padding-bottom:8px;border-bottom:1px solid rgba(211,171,91,.16)}.smart-rules-intro strong{font-family:Georgia,serif;color:#f1cf86;font-size:1rem}.smart-rules-intro small{font-size:.64rem;color:#8f8678}.smart-rule-card{display:grid!important;grid-template-columns:24px minmax(0,1fr);gap:8px;margin:7px 0!important;padding:9px!important;border:1px solid rgba(203,151,65,.17)!important;border-radius:10px!important;background:rgba(85,54,25,.18)!important}.smart-rule-icon{width:22px;height:22px;display:grid;place-items:center;border-radius:50%;background:rgba(153,91,31,.28);border:1px solid rgba(230,169,77,.5);color:#efb45c;font-weight:900;font-size:.75rem}.smart-rule-copy{min-width:0}.smart-rule-copy>strong{display:block;color:#e8d5aa;font-size:.78rem;line-height:1.25}.smart-rule-copy p{display:block!important;margin:4px 0 7px!important;padding:0!important;border:0!important;background:transparent!important;color:#aaa091!important;font-size:.69rem!important;line-height:1.38!important}.smart-rule-action{min-height:29px!important;width:auto!important;margin:0!important;padding:5px 9px!important;border-radius:8px!important;font-size:.63rem!important;background:rgba(255,255,255,.025)!important;border-color:rgba(211,171,91,.24)!important;color:#ccb987!important}.smart-rule-action.is-fix{background:rgba(85,145,104,.12)!important;border-color:rgba(112,180,129,.3)!important;color:#b9d5b8!important}`;document.head.appendChild(s);let queued=false;const queue=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{queued=false;render()}))};['classesEditor','skillsEditor','equipmentEditor'].forEach(id=>{const el=$(id);if(el){el.addEventListener('input',queue);el.addEventListener('change',queue);new MutationObserver(queue).observe(el,{childList:true})}});$('level')?.addEventListener('input',queue);$('level')?.addEventListener('change',queue);window.addEventListener('pageshow',queue,{passive:true});setTimeout(render,100);setTimeout(render,700)}
 install();
})();