// High Fantasy Symbolist support — learned symbols, active symbol tracking, and Actions integration.
(function(){
  const $=id=>document.getElementById(id), norm=v=>String(v||'').trim().toLowerCase(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rows=id=>[...($(id)?.querySelectorAll('.entry-row')||[])], vals=r=>[...r.querySelectorAll('input,textarea,select')].map(x=>String(x.value||'').trim());
  const ALL=[
    ['Symbol of Binding','Current Attribute die sizes cannot exceed corresponding base Attribute die sizes.'],
    ['Symbol of Creation','During a conflict, destroy this symbol instead of spending Inventory Points.'],
    ['Symbol of Despair','During conflicts, HP/MP recovery is halved.'],
    ['Symbol of Destiny','After a visible bearer makes a non-critical/non-fumble Check, spend 1 FP to force a reroll of both dice; once per Check.'],
    ['Symbol of Elements','Choose air, bolt, dark, earth, fire, ice, light, or poison. When bearer deals damage, you may spend MP equal to one third of total damage to change all that damage to the chosen type.'],
    ['Symbol of Enmity','While bearer is in Crisis, visible enemies must include them among targets of attacks/offensive spells if possible.'],
    ['Symbol of Flux','Choose dazed, shaken, slow, or weak; bearer either gains immunity to it, or loses/cannot gain immunity to it.'],
    ['Symbol of Forbiddance','Choose Attack, Guard, Objective, Spell, or Skill. Bearer loses HP and MP before using that action: 5 each, 10 each at level 20+, 20 each at level 40+.'],
    ['Symbol of Growth','Spells targeting up to three creatures cast by bearer may target up to four; additional MP is still required for the fourth target.'],
    ['Symbol of Metamorphosis','Choose beast, construct, demon, elemental, monster, plant, or undead. Bearer is treated as that Species for Skills/effects. Cannot be applied to PCs.'],
    ['Symbol of Prosperity','When bearer spends 1 FP to invoke a Trait or Bond, they also receive 100 zenit.'],
    ['Symbol of Protection','Choose air, bolt, dark, earth, fire, ice, light, or poison. Bearer gains Resistance to that damage type.'],
    ['Symbol of Rebellion','If a Villain is present, bearer’s Opposed Checks critically succeed on doubles unless the Check is a fumble.'],
    ['Symbol of Rebirth','When bearer would be reduced to 0 HP, they may destroy this symbol to be reduced to exactly 1 HP instead.'],
    ['Symbol of Revenge','When a creature in Crisis hits bearer with an attack/offensive spell, that creature recovers 5 HP and 5 MP.'],
    ['Symbol of Sacrifice','When bearer suffers damage and you can see them, destroy this symbol to suffer the same amount instead.'],
    ['Symbol of Sorcery','Total MP cost of spells targeting bearer is reduced by 5 MP, minimum total 5 MP; cumulative across multiple bearers.'],
    ['Symbol of Truth','Checks to examine/locate bearer and Accuracy/Magic Checks targeting bearer gain +2; cumulative across multiple bearers.'],
    ['Symbol of Weakness','Choose air, bolt, dark, earth, fire, ice, light, or poison. Bearer suffers 5 extra damage from that type.']
  ];
  const marker='§AESTRASYS:';
  const symbolist=()=>rows('classesEditor').some(r=>norm(vals(r)[0])==='symbolist');
  function symbolismRow(){return rows('skillsEditor').find(r=>norm(vals(r)[0])==='symbolism'&&norm(vals(r)[2])==='symbolist')||rows('skillsEditor').find(r=>norm(vals(r)[0])==='symbolism')}
  function symbolismSL(){const r=symbolismRow();return r?Math.max(0,Number(vals(r)[1])||0):0}
  function readMeta(){const r=symbolismRow();if(!r)return{learned:[],active:[]};const fields=[...r.querySelectorAll('input,textarea,select')],el=fields[3];const text=String(el?.value||'');const m=text.match(/§AESTRASYS:([^\n]+)/);if(!m)return{learned:[],active:[]};try{return JSON.parse(atob(m[1]))}catch{return{learned:[],active:[]}}}
  function writeMeta(data){const r=symbolismRow();if(!r)return;const fields=[...r.querySelectorAll('input,textarea,select')],el=fields[3];if(!el)return;let text=String(el.value||'').replace(/\n?§AESTRASYS:[^\n]+/g,'').trim();const blob=btoa(unescape(encodeURIComponent(JSON.stringify(data))));el.value=(text?text+'\n':'')+marker+blob;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}
  function meta(){const m=readMeta();return{learned:Array.isArray(m.learned)?m.learned:[],active:Array.isArray(m.active)?m.active:[]}}
  function modal(){let m=$('symbolistModal');if(m)return m;m=document.createElement('div');m.id='symbolistModal';m.className='sym-modal hidden';m.innerHTML='<div class="sym-dialog"><button class="sym-close" type="button">×</button><div id="symBody"></div></div>';document.body.appendChild(m);m.querySelector('.sym-close').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};return m}
  function openConfigure(){const m=modal(),b=$('symBody'),sl=symbolismSL(),limit=sl*2,state=meta();b.innerHTML=`<p class="eyebrow">High Fantasy · Symbolist</p><h2>Learned Symbols</h2><p class="sym-help">Symbolism SL ${sl}: learn up to <strong>${limit}</strong> symbols.</p><div class="sym-grid">${ALL.map(([n,d])=>`<label class="sym-choice"><input type="checkbox" value="${esc(n)}" ${state.learned.includes(n)?'checked':''}><span><strong>${esc(n)}</strong><small>${esc(d)}</small></span></label>`).join('')}</div><div class="sym-footer"><span id="symLearnCount">${state.learned.length} / ${limit}</span><button class="primary" id="symSaveLearned" type="button">Save repertoire</button></div>`;const checks=[...b.querySelectorAll('.sym-choice input')];const count=()=>{const n=checks.filter(x=>x.checked).length;$('symLearnCount').textContent=`${n} / ${limit}`;checks.forEach(x=>{if(!x.checked)x.disabled=n>=limit})};checks.forEach(x=>x.onchange=count);count();$('symSaveLearned').onclick=()=>{const learned=checks.filter(x=>x.checked).map(x=>x.value);writeMeta({...state,learned});m.classList.add('hidden');queue()};m.classList.remove('hidden')}
  function openActive(){const m=modal(),b=$('symBody'),sl=symbolismSL(),max=sl+1,state=meta();b.innerHTML=`<p class="eyebrow">High Fantasy · Symbolist</p><h2>Active Symbols</h2><p class="sym-help">You may have up to <strong>${max}</strong> active symbols at once. Creating a symbol costs 2 IP and uses the Inventory action.</p><div class="sym-active-list">${state.active.map((a,i)=>`<article><div><strong>${esc(a.symbol)}</strong><small>${esc(a.target||'Unknown bearer')}</small>${a.choice?`<small>${esc(a.choice)}</small>`:''}</div><button type="button" data-sym-destroy="${i}">Destroy</button></article>`).join('')||'<p class="muted">No active symbols.</p>'}</div><hr><h3>Create symbol</h3><label>Symbol<select id="symCreateSymbol">${state.learned.map(n=>`<option>${esc(n)}</option>`).join('')}</select></label><label>Bearer / target<input id="symCreateTarget" placeholder="Self, Iris, Enemy 1…"></label><label>Choice / note<input id="symCreateChoice" placeholder="e.g. fire, shaken, Spell"></label><button class="primary" id="symCreateBtn" type="button" ${!state.learned.length||state.active.length>=max?'disabled':''}>Create active symbol</button>`;b.querySelectorAll('[data-sym-destroy]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.symDestroy),next=meta();next.active.splice(i,1);writeMeta(next);openActive();queue()});$('symCreateBtn').onclick=()=>{const next=meta();if(next.active.length>=max)return;const symbol=$('symCreateSymbol').value,target=$('symCreateTarget').value.trim(),choice=$('symCreateChoice').value.trim();next.active.push({symbol,target,choice});writeMeta(next);openActive();queue()};m.classList.remove('hidden')}
  function panel(){const old=document.querySelector('.symbolist-build-tools');if(!symbolist()||!symbolismRow()){old?.remove();return}const body=$('buildMenuBody');if(!body)return;const section=document.querySelector('.build-tab.active')?.dataset.build;if(section!=='classes'&&section!=='skills'){old?.remove();return}const hierarchy=$('classHierarchy'),actions=body.querySelector('.build-actions');if(!hierarchy&&!actions)return;let box=old;if(!box){box=document.createElement('section');box.className='symbolist-build-tools';(hierarchy||actions).insertAdjacentElement(hierarchy?'beforebegin':'afterend',box)}const s=meta(),sl=symbolismSL();box.innerHTML=`<div><p class="eyebrow">Symbolist</p><strong>Symbol Workshop</strong><small>${s.learned.length}/${sl*2} learned · ${s.active.length}/${sl+1} active</small></div><div class="sym-tools"><button type="button" class="secondary sym-configure">Configure</button><button type="button" class="secondary sym-active">Active symbols</button></div>`;box.querySelector('.sym-configure').onclick=openConfigure;box.querySelector('.sym-active').onclick=openActive}
  function actionCard(){const host=$('sessionActionBody');if(!host)return;const mode=host.dataset.mode;if(!symbolist()||!symbolismRow()||!['skills','favourites'].includes(mode)){host.querySelector('[data-symbolist-action]')?.remove();return}if(host.querySelector('[data-symbolist-action]'))return;const card=document.createElement('article');card.className='a2-card symbolist-action-card';card.dataset.symbolistAction='1';card.innerHTML='<button class="a2-open" type="button"><span class="a2-kind">✧ SKILL · SYMBOLIST</span><strong>Symbol Workshop</strong><small>High Fantasy · Symbolism</small><p>Create, review, and destroy your active symbols.</p><span class="a2-more">Open workshop ›</span></button>';card.querySelector('button').onclick=e=>{e.stopPropagation();openActive()};host.prepend(card)}
  const style=document.createElement('style');style.textContent=`.symbolist-build-tools{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 10px;padding:11px 13px;border:1px solid rgba(211,171,91,.3);border-radius:11px;background:linear-gradient(110deg,rgba(67,46,92,.14),rgba(45,77,85,.10))}.symbolist-build-tools>div:first-child{display:grid;gap:2px}.sym-tools{display:flex;gap:8px}.sym-modal{position:fixed;inset:0;z-index:2350;display:grid;place-items:center;padding:14px;background:rgba(2,4,8,.87)}.sym-modal.hidden{display:none!important}.sym-dialog{position:relative;width:min(900px,96vw);max-height:90vh;overflow:auto;padding:25px 22px;border:1px solid rgba(211,171,91,.4);border-radius:18px;background:linear-gradient(145deg,#11151d,#1a141b)}.sym-close{position:absolute!important;right:11px;top:11px;width:36px!important;height:36px!important;min-height:0!important;padding:0!important;border-radius:50%!important}.sym-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:14px 0}.sym-choice{display:flex!important;gap:9px;align-items:flex-start;padding:10px;border:1px solid rgba(211,171,91,.18);border-radius:10px;background:rgba(255,255,255,.025)}.sym-choice input{margin-top:3px}.sym-choice span{display:grid;gap:3px}.sym-choice small{font-size:.68rem;line-height:1.35;opacity:.72}.sym-footer{display:flex;justify-content:space-between;align-items:center;gap:12px}.sym-active-list{display:grid;gap:8px}.sym-active-list article{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:10px;border:1px solid rgba(211,171,91,.18);border-radius:10px}.sym-active-list article>div{display:grid;gap:2px}.sym-active-list small{opacity:.68}.symbolist-action-card{border-color:rgba(167,132,210,.35)!important}@media(max-width:640px){.symbolist-build-tools{align-items:stretch;flex-direction:column}.sym-tools{display:grid;grid-template-columns:1fr 1fr}.sym-grid{grid-template-columns:1fr}.sym-footer{align-items:stretch;flex-direction:column}.sym-footer button{width:100%}}`;document.head.appendChild(style);
  function queue(){requestAnimationFrame(()=>{panel();actionCard()})}
  function boot(){const body=$('buildMenuBody');if(!body){setTimeout(boot,100);return}['classesEditor','skillsEditor'].forEach(id=>{const el=$(id);if(el){el.addEventListener('input',queue);el.addEventListener('change',queue);new MutationObserver(queue).observe(el,{childList:true})}});new MutationObserver(queue).observe(body,{childList:true,subtree:false});const actions=$('sessionActionBody');if(actions)new MutationObserver(()=>requestAnimationFrame(actionCard)).observe(actions,{childList:true});document.addEventListener('click',e=>{if(e.target.closest?.('.build-tab,.build-cycle,[data-action-tab]'))setTimeout(queue,0)},true);queue()}
  boot();
})();